import type { Occasion, GiftType, Recipient, Product, Category } from './types';
import {
  Gift, Shirt, Smartphone, HomeIcon as HomeIconLucide, ToyBrick, Gem, Users, ShoppingBag, Cloud, Snowflake, Book,
  MapPin, HelpCircle, Briefcase, Percent, Star, User, Heart,
  Cake, CalendarDays, Camera, Car, Crown, Drama, Feather, Flag, Flower, Gamepad,
  Globe, GraduationCap, HandHeart, History, Lamp, Leaf, Medal, Moon,
  Mountain, Music, Newspaper, Package, Palette, PartyPopper, Pencil,
  Pin, Plane, Puzzle, Rocket, School, Search, Shield, Smile, Sparkles as SparklesIcon,
  Sprout, Store, Sun, Tag, ThumbsUp, Ticket, TreeDeciduous, Trophy,
  Utensils, Wand, Watch, Wind, Wine, Zap, Anchor, Award, Baby,
} from 'lucide-react';

export const OCCASIONS_LIST: Occasion[] = [
  // Personal
  { id: 'birthday', name: 'Birthday', slug: 'birthday', Icon: PartyPopper, dataAiHint: "birthday party" },
  { id: 'anniversary', name: 'Anniversary', slug: 'anniversary', Icon: Gift, dataAiHint: "anniversary celebration" },
  { id: 'wedding', name: 'Wedding', slug: 'wedding', Icon: Users, dataAiHint: "wedding ceremony" },
  { id: 'farewell', name: 'Farewell', slug: 'farewell', Icon: Plane, dataAiHint: "farewell party plane" },
  { id: 'house-warming', name: 'House Warming', slug: 'house-warming', Icon: HomeIconLucide, dataAiHint: "new home gift" },
  { id: 'baby-shower', name: 'Baby Shower', slug: 'baby-shower', Icon: Baby, dataAiHint: "baby shower gift" },
  { id: 'graduation', name: 'Graduation', slug: 'graduation', Icon: GraduationCap, dataAiHint: "graduation ceremony" },

  // Special Days
  { id: 'fathers-day', name: "Father's Day", slug: 'fathers-day', Icon: Trophy, dataAiHint: "father child trophy" },
  { id: 'valentines-day', name: "Valentine's Day", slug: 'valentines-day', Icon: Heart, dataAiHint: "valentine romance" },
  { id: 'mothers-day', name: "Mother's Day", slug: 'mothers-day', Icon: Star, dataAiHint: "mother child star" },
  { id: 'womens-day', name: "Women's Day", slug: 'womens-day', Icon: Award, dataAiHint: "women empowerment award" },
  { id: 'brothers-day', name: "Brother's Day", slug: 'brothers-day', Icon: Shield, dataAiHint: "brother shield bond" },
  { id: 'parents-day', name: "Parents' Day", slug: 'parents-day', Icon: Users, dataAiHint: "happy family parents" },
  { id: 'friendship-day', name: "Friendship Day", slug: 'friendship-day', Icon: HandHeart, dataAiHint: "friends handshake" },
  { id: 'teachers-day', name: "Teacher's Day", slug: 'teachers-day', Icon: GraduationCap, dataAiHint: "teacher student book" },
  { id: 'childrens-day', name: "Children's Day", slug: 'childrens-day', Icon: Smile, dataAiHint: "happy children playing" },
  { id: 'new-year', name: 'New Year', slug: 'new-year', Icon: PartyPopper, dataAiHint: "new year fireworks" },
  { id: 'grandparents-day', name: "Grandparents' Day", slug: 'grandparents-day', Icon: Users, dataAiHint: "elderly couple love" },

  // Festivals
  { id: 'rakhi', name: 'Rakhi', slug: 'rakhi', Icon: Gift, dataAiHint: "rakhi thread festival" },
  { id: 'durga-puja', name: 'Durga Puja', slug: 'durga-puja', Icon: Drama, dataAiHint: "durga idol pandal" },
  { id: 'karva-chauth', name: 'Karva Chauth', slug: 'karva-chauth', Icon: Moon, dataAiHint: "karva chauth ritual moon" },
  { id: 'diwali-bhaidooj', name: 'Diwali & Bhaidooj', slug: 'diwali-bhaidooj', Icon: Lamp, dataAiHint: "diwali lights diya" },
  { id: 'christmas', name: 'Christmas', slug: 'christmas', Icon: TreeDeciduous, dataAiHint: "christmas tree gifts" },
  { id: 'holi', name: 'Holi', slug: 'holi', Icon: Palette, dataAiHint: "holi colors festival" },
  { id: 'poila-baisakh', name: 'Poila Baisakh', slug: 'poila-baisakh', Icon: CalendarDays, dataAiHint: "bengali new year calendar" },
  { id: 'onam', name: 'Onam', slug: 'onam', Icon: Flower, dataAiHint: "onam pookalam festival" },
  { id: 'bihu', name: 'Bihu', slug: 'bihu', Icon: Music, dataAiHint: "bihu dance music" },

  // Corporate specific occasions can also be gift types
  { id: 'corporate-welcome-kits', name: 'Welcome Kits (Occasion)', slug: 'corporate-welcome-kits', Icon: Package, dataAiHint: "corporate welcome basket" },
  { id: 'corporate-memento-event', name: 'Memento Event', slug: 'corporate-memento-event', Icon: Award, dataAiHint: "event memento" },
  { id: 'corporate-awards-ceremony', name: 'Awards Ceremony', slug: 'corporate-awards-ceremony', Icon: Trophy, dataAiHint: "trophy awards night" },
  { id: 'party', name: 'Party', slug: 'party', Icon: PartyPopper, dataAiHint: "celebration party" },
  { id: 'monsoon', name: 'Monsoon', slug: 'monsoon', Icon: Cloud, dataAiHint: "rainy season gift" },
  { id: 'winter', name: 'Winter', slug: 'winter', Icon: Snowflake, dataAiHint: "winter season gift" },
  { id: 'sports-event', name: 'Sports Event', slug: 'sports-event', Icon: Gamepad, dataAiHint: "sports competition gift" },
  { id: 'spring', name: 'Spring', slug: 'spring', Icon: Sprout, dataAiHint: "spring season gift" },
  { id: 'summer', name: 'Summer', slug: 'summer', Icon: Sun, dataAiHint: "summer season gift" },
  { id: 'corporate-event', name: 'Corporate Event', slug: 'corporate-event', Icon: Briefcase, dataAiHint: "business event gift" },
  { id: 'trade-show', name: 'Trade Show', slug: 'trade-show', Icon: Briefcase, dataAiHint: "trade show giveaway" },
  { id: 'conference', name: 'Conference', slug: 'conference', Icon: Briefcase, dataAiHint: "conference gift" },
  { id: 'pet-birthday', name: 'Pet Birthday', slug: 'pet-birthday', Icon: Smile, dataAiHint: "pet birthday gift" },
  { id: 'new-pet', name: 'New Pet', slug: 'new-pet', Icon: Smile, dataAiHint: "new pet gift" },
  { id: 'honeymoon', name: 'Honeymoon', slug: 'honeymoon', Icon: Heart, dataAiHint: "honeymoon gift" },
  { id: 'dinner-party', name: 'Dinner Party', slug: 'dinner-party', Icon: Utensils, dataAiHint: "dinner party gift" },
];

export const GIFT_TYPES_LIST: GiftType[] = [
  { id: 'pebble-art', name: 'Pebble Art', slug: 'pebble-art', Icon: Gem, dataAiHint: "stone art craft" },
  { id: 'mini-you-series', name: 'Mini You Series', slug: 'mini-you-series', Icon: ToyBrick, dataAiHint: "3d miniature figure" },
  { id: '3d-crystals', name: '3D Crystals', slug: '3d-crystals', Icon: Gem, dataAiHint: "crystal engraving gift" },
  { id: 'photo-lamps', name: 'Photo Lamps', slug: 'photo-lamps', Icon: Lamp, dataAiHint: "custom 3d light" },
  { id: 'photo-gifts-general', name: 'Photo Gifts (General)', slug: 'photo-gifts-general', Icon: Gift, dataAiHint: "personalized photo present" },
  { id: 'photo-frames', name: 'Photo Frames', slug: 'photo-frames', Icon: Camera, dataAiHint: "picture frame decor" },
  { id: 'photobook-album', name: 'Photobook Album', slug: 'photobook-album', Icon: Newspaper, dataAiHint: "custom photo album" },
  { id: 'photo-clocks', name: 'Photo Clocks', slug: 'photo-clocks', Icon: Watch, dataAiHint: "wall clock custom" },
  { id: 'gift-hampers', name: 'Gift Hampers', slug: 'gift-hampers', Icon: Package, dataAiHint: "gift basket hamper" },
  { id: 'resin-art', name: 'Resin Art', slug: 'resin-art', Icon: Palette, dataAiHint: "epoxy resin craft" },
  { id: 'shadow-box', name: 'Shadow Box', slug: 'shadow-box', Icon: Package, dataAiHint: "3d shadow box frame" },
  { id: 'spotify-gifts', name: 'Spotify Gifts', slug: 'spotify-gifts', Icon: Music, dataAiHint: "spotify music plaque" },
  { id: 'heart-shaped-gifts', name: 'Heart Shaped Gifts', slug: 'heart-shaped-gifts', Icon: Heart, dataAiHint: "heart shape present" },
  { id: 'wooden-gifts', name: 'Wooden Gifts', slug: 'wooden-gifts', Icon: Shield, dataAiHint: "engraved wood item" },
  { id: 'chocolates', name: 'Chocolates', slug: 'chocolates', Icon: Gift, dataAiHint: "gourmet chocolate box" },
  { id: 'utility-mugs', name: 'Utility Gifts: Mugs', slug: 'utility-mugs', Icon: Utensils, dataAiHint: "custom coffee mug" },
  { id: 'utility-pens', name: 'Utility Gifts: Pens', slug: 'utility-pens', Icon: Pencil, dataAiHint: "engraved pen luxury" },
  { id: 'utility-t-shirts', name: 'Utility Gifts: T-Shirts', slug: 'utility-t-shirts', Icon: Shirt, dataAiHint: "custom printed tshirt" },
  { id: 'utility-bottles', name: 'Utility Gifts: Bottles', slug: 'utility-bottles', Icon: Package, dataAiHint: "personalized water bottle" },
  { id: 'utility-diaries', name: 'Utility Gifts: Diaries', slug: 'utility-diaries', Icon: Newspaper, dataAiHint: "custom journal diary" },
  { id: 'utility-keychains', name: 'Utility Gifts: Key Chains', slug: 'utility-keychains', Icon: Anchor, dataAiHint: "custom photo keychain" },
  { id: 'home-living-lamps', name: 'Home & Living: Lamps', slug: 'home-living-lamps', Icon: Lamp, dataAiHint: "decorative table lamp" },
  { id: 'home-living-clocks', name: 'Home & Living: Clocks', slug: 'home-living-clocks', Icon: Watch, dataAiHint: "stylish wall clock" },
  { id: 'home-living-cushions', name: 'Home & Living: Cushions', slug: 'home-living-cushions', Icon: ToyBrick, dataAiHint: "personalized photo cushion" },
  { id: 'home-living-bar-accessories', name: 'Home & Living: Bar Accessories', slug: 'home-living-bar-accessories', Icon: Wine, dataAiHint: "barware tools set" },
  { id: 'home-living-name-plates', name: 'Home & Living: Name Plates', slug: 'home-living-name-plates', Icon: Pin, dataAiHint: "custom door nameplate" },
  { id: 'home-living-magnets-tags', name: 'Home & Living: Magnets & Tags', slug: 'home-living-magnets-tags', Icon: Tag, dataAiHint: "fridge magnet custom" },
  { id: 'home-decor', name: 'Home Decor (General)', slug: 'home-decor', Icon: HomeIconLucide, dataAiHint: "stylish home decor" },
  { id: 'mini-you-bobbleheads', name: 'Mini You: Bobbleheads', slug: 'mini-you-bobbleheads', Icon: User, dataAiHint: "custom bobblehead doll" },
  { id: 'mini-you-caricatures', name: 'Mini You: Caricatures', slug: 'mini-you-caricatures', Icon: Smile, dataAiHint: "funny caricature art" },
  { id: 'mini-you-miniatures', name: 'Mini You: Full/Half Miniatures', slug: 'mini-you-miniatures', Icon: ToyBrick, dataAiHint: "3d selfie miniature" },
  { id: 'mini-you-framed-bobbleheads', name: 'Mini You: Framed Bobbleheads', slug: 'mini-you-framed-bobbleheads', Icon: User, dataAiHint: "bobblehead display case" },
  { id: 'mini-you-realistic-busts', name: 'Mini You: Realistic Busts', slug: 'mini-you-realistic-busts', Icon: User, dataAiHint: "custom bust statue" },
  { id: 'corporate-awards', name: 'Corporate: Awards', slug: 'corporate-awards', Icon: Award, dataAiHint: "trophy plaque award" },
  { id: 'corporate-trophies', name: 'Corporate: Trophies', slug: 'corporate-trophies', Icon: Trophy, dataAiHint: "company trophy recognition" },
  { id: 'corporate-certificates', name: 'Corporate: Certificates', slug: 'corporate-certificates', Icon: Medal, dataAiHint: "achievement certificate frame" },
  { id: 'corporate-medals', name: 'Corporate: Medals', slug: 'corporate-medals', Icon: Medal, dataAiHint: "engraved medal award" },
  { id: 'corporate-mementos', name: 'Corporate: Mementos', slug: 'corporate-mementos', Icon: Gift, dataAiHint: "commemorative memento gift" },
  { id: 'corporate-apparel-tshirts', name: 'Corporate: T-Shirts', slug: 'corporate-apparel-tshirts', Icon: Shirt, dataAiHint: "branded company tshirt" },
  { id: 'corporate-apparel-caps', name: 'Corporate: Caps', slug: 'corporate-apparel-caps', Icon: Award, dataAiHint: "custom logo cap" },
  { id: 'corporate-apparel-backpacks', name: 'Corporate: Backpacks', slug: 'corporate-apparel-backpacks', Icon: ShoppingBag, dataAiHint: "company logo backpack" },
  { id: 'corporate-joining-kits', name: 'Corporate: Joining Kits', slug: 'corporate-joining-kits', Icon: Package, dataAiHint: "employee welcome kit" },
  { id: 'corporate-joining-kits-2in1', name: 'Corporate: Joining Kits (2-in-1)', slug: 'corporate-joining-kits-2in1', Icon: Package, dataAiHint: "2in1 welcome set" },
  { id: 'corporate-joining-kits-3in1', name: 'Corporate: Joining Kits (3-in-1)', slug: 'corporate-joining-kits-3in1', Icon: Package, dataAiHint: "3in1 welcome set" },
  { id: 'corporate-joining-kits-4in1', name: 'Corporate: Joining Kits (4-in-1)', slug: 'corporate-joining-kits-4in1', Icon: Package, dataAiHint: "4in1 welcome set" },
  { id: 'corporate-stationery-stamps', name: 'Corporate: Rubber Stamps', slug: 'corporate-stationery-stamps', Icon: Pencil, dataAiHint: "company rubber stamp" },
  { id: 'corporate-stationery-pens', name: 'Corporate: Pens', slug: 'corporate-stationery-pens', Icon: Pencil, dataAiHint: "branded corporate pen" },
  { id: 'corporate-stationery-penstands', name: 'Corporate: Pen Stands', slug: 'corporate-stationery-penstands', Icon: Briefcase, dataAiHint: "desk pen holder" },
  { id: 'corporate-stationery-diaries', name: 'Corporate: Diaries', slug: 'corporate-stationery-diaries', Icon: Newspaper, dataAiHint: "custom logo diary" },
  { id: 'corporate-stationery-calendars', name: 'Corporate: Calendars', slug: 'corporate-stationery-calendars', Icon: CalendarDays, dataAiHint: "company desk calendar" },
  { id: 'corporate-stationery-cards', name: 'Corporate: ID & Visiting Cards', slug: 'corporate-stationery-cards', Icon: User, dataAiHint: "business visiting card" },
  { id: 'corporate-drinkware-bottles', name: 'Corporate: Bottles', slug: 'corporate-drinkware-bottles', Icon: Package, dataAiHint: "branded water bottle" },
  { id: 'corporate-drinkware-mugs', name: 'Corporate: Mugs', slug: 'corporate-drinkware-mugs', Icon: Utensils, dataAiHint: "company logo mug" },
  { id: 'corporate-utility-gift-sets', name: 'Corporate: Utility Gift Sets', slug: 'corporate-utility-gift-sets', Icon: Package, dataAiHint: "executive gift set" },
  { id: 'corporate-utility-desk-clocks', name: 'Corporate: Desk Clocks', slug: 'corporate-utility-desk-clocks', Icon: Watch, dataAiHint: "corporate desk clock" },
  { id: 'corporate-utility-desk-organizers', name: 'Corporate: Desk Organizers', slug: 'corporate-utility-desk-organizers', Icon: Briefcase, dataAiHint: "office desk organizer" },
  { id: 'corporate-utility-name-plates', name: 'Corporate: Name Plates', slug: 'corporate-utility-name-plates', Icon: Pin, dataAiHint: "desk name plate" },
  { id: 'corporate-utility-keychains', name: 'Corporate: Key Chains', slug: 'corporate-utility-keychains', Icon: Anchor, dataAiHint: "company logo keychain" },
  { id: 'corporate-utility-name-badges', name: 'Corporate: Name Badges', slug: 'corporate-utility-name-badges', Icon: User, dataAiHint: "employee name badge" },
  { id: 'apparel', name: 'Apparel (General)', slug: 'apparel', Icon: Shirt, dataAiHint: "clothing fashion style" },
  { id: 'stationery', name: 'Stationery (General)', slug: 'stationery', Icon: Pencil, dataAiHint: "office desk supplies" },
  { id: 'drinkware', name: 'Drinkware (General)', slug: 'drinkware', Icon: Utensils, dataAiHint: "cups bottles glasses" },
  { id: 'accessories', name: 'Accessories (General)', slug: 'accessories', Icon: SparklesIcon, dataAiHint: "fashion personal items" },
  { id: 'pet-gifts', name: 'Pet Gifts', slug: 'pet-gifts', Icon: Smile, dataAiHint: "dog cat toys" },
  { id: 'travel-gear', name: 'Travel Gear', slug: 'travel-gear', Icon: Plane, dataAiHint: "luggage travel essentials" },
  { id: 'sports-fitness', name: 'Sports & Fitness', slug: 'sports-fitness', Icon: Zap, dataAiHint: "gym equipment sports" },
  { id: 'outdoor-garden', name: 'Outdoor & Garden', slug: 'outdoor-garden', Icon: Sprout, dataAiHint: "plants garden tools" },
  { id: 'tech-gadgets', name: 'Tech & Gadgets', slug: 'tech-gadgets', Icon: Smartphone, dataAiHint: "electronic devices tech" },
  { id: 'event-supplies', name: 'Event Supplies', slug: 'event-supplies', Icon: Ticket, dataAiHint: "party wedding decor" },
];

export const RECIPIENTS_LIST: Recipient[] = [
  { id: 'men', name: 'Men (All)', slug: 'men', Icon: User, dataAiHint: "man silhouette" },
  { id: 'husband', name: 'Husband', slug: 'husband', Icon: Heart, dataAiHint: "loving couple husband" },
  { id: 'father', name: 'Father', slug: 'father', Icon: Award, dataAiHint: "father figure award" },
  { id: 'boyfriend', name: 'Boyfriend', slug: 'boyfriend', Icon: Rocket, dataAiHint: "romantic gift boyfriend" },
  { id: 'brother', name: 'Brother', slug: 'brother', Icon: Shield, dataAiHint: "siblings bond brother" },
  { id: 'son', name: 'Son', slug: 'son', Icon: GraduationCap, dataAiHint: "young boy son" },
  { id: 'male-friend', name: 'Male Friend', slug: 'male-friend', Icon: Users, dataAiHint: "friends group male" },
  { id: 'grandfather', name: 'Grandfather', slug: 'grandfather', Icon: User, dataAiHint: "elderly man grandfather" },
  { id: 'kids-boys', name: 'Kids (Boys)', slug: 'kids-boys', Icon: ToyBrick, dataAiHint: "playing boy child" },
  { id: 'women', name: 'Women (All)', slug: 'women', Icon: ShoppingBag, dataAiHint: "woman silhouette shopping" },
  { id: 'wife', name: 'Wife', slug: 'wife', Icon: Gem, dataAiHint: "happy couple wife" },
  { id: 'mother', name: 'Mother', slug: 'mother', Icon: Flower, dataAiHint: "motherly love flower" },
  { id: 'girlfriend', name: 'Girlfriend', slug: 'girlfriend', Icon: SparklesIcon, dataAiHint: "couple in love girlfriend" },
  { id: 'sister', name: 'Sister', slug: 'sister', Icon: Feather, dataAiHint: "sisters together feather" },
  { id: 'daughter', name: 'Daughter', slug: 'daughter', Icon: Star, dataAiHint: "young girl daughter" },
  { id: 'female-friend', name: 'Female Friend', slug: 'female-friend', Icon: Users, dataAiHint: "female friends group" },
  { id: 'grandmother', name: 'Grandmother', slug: 'grandmother', Icon: User, dataAiHint: "elderly woman grandmother" },
  { id: 'kids-girls', name: 'Kids (Girls)', slug: 'kids-girls', Icon: Smile, dataAiHint: "smiling girl child" },
  { id: 'couples', name: 'Couples', slug: 'couples', Icon: Users, dataAiHint: "romantic couple gift" },
  { id: 'winner', name: 'Winner', slug: 'winner', Icon: Trophy, dataAiHint: "trophy award winner" },
  { id: 'employee', name: 'Employee', slug: 'employee', Icon: Briefcase, dataAiHint: "corporate employee gift"},
  { id: 'client', name: 'Client', slug: 'client', Icon: HandHeart, dataAiHint: "business client appreciation"},
  { id: 'teacher', name: 'Teacher', slug: 'teacher', Icon: GraduationCap, dataAiHint: "teacher appreciation gift"},
  { id: 'pet', name: 'Pet', slug: 'pet', Icon: Smile, dataAiHint: "dog cat pet gift"},
  { id: 'family', name: 'Family', slug: 'family', Icon: HomeIconLucide, dataAiHint: "family group gift" },
  { id: 'student', name: 'Student', slug: 'student', Icon: Book, dataAiHint: "student gift" },
  { id: 'gamer', name: 'Gamer', slug: 'gamer', Icon: Gamepad, dataAiHint: "gamer gift" },
  { id: 'traveler', name: 'Traveler', slug: 'traveler', Icon: Plane, dataAiHint: "traveler gift" },
  { id: 'gardener', name: 'Gardener', slug: 'gardener', Icon: Leaf, dataAiHint: "gardener gift" },
  { id: 'homeowner', name: 'Homeowner', slug: 'homeowner', Icon: HomeIconLucide, dataAiHint: "homeowner gift" },
  { id: 'business', name: 'Business', slug: 'business', Icon: Briefcase, dataAiHint: "business gift" },
  { id: 'organizer', name: 'Organizer', slug: 'organizer', Icon: CalendarDays, dataAiHint: "event organizer gift" },
  { id: 'boss', name: 'Boss', slug: 'boss', Icon: Briefcase, dataAiHint: "boss gift" },
];

export const CATEGORIES: Category[] = GIFT_TYPES_LIST.map(gt => ({...gt}));

export const PRODUCTS: Product[] = [
  {
    id: '3d-crystal-buddha-petal-base-001',
    name: '3D Crystal Buddha Petal Base',
    slug: '3d-crystal-buddha-petal-base',
    description: 'An exquisite 3D laser-engraved Buddha in a crystal petal base, perfect for bringing peace and serenity to any space.',
    price: 2499,
    category: '3d-crystals',
    occasion: ['house-warming', 'birthday', 'wedding', 'diwali-bhaidooj'],
    recipient: ['men', 'women', 'family', 'parents-day'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'crystal buddha statue',
    popularity: 85,
    trending: true,
  },
  {
    id: 'mini-you-caricature-single-002',
    name: 'Mini You Series Caricature Figure (Single Person, 8 cm)',
    slug: 'mini-you-caricature-single-8cm',
    description: 'A fun and personalized 8cm caricature figure that captures the unique essence of an individual. A delightful gift for any occasion.',
    price: 1199,
    category: 'mini-you-caricatures',
    occasion: ['birthday', 'anniversary', 'farewell', 'graduation'],
    recipient: ['friends', 'colleagues', 'couples', 'male-friend', 'female-friend'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'custom caricature figure',
    popularity: 92,
    trending: true,
  },
  {
    id: '3d-moon-lamp-wife-birthday-003',
    name: 'Personalised 3D Moon Lamp for Wife Birthday (14 cm, 16 colours)',
    slug: 'personalised-3d-moon-lamp-wife-birthday',
    description: 'Light up her world with this magical 14cm personalized 3D moon lamp, featuring 16 color options. The perfect romantic gift.',
    price: 2499,
    category: 'photo-lamps',
    occasion: ['birthday', 'valentines-day', 'anniversary'],
    recipient: ['wife', 'girlfriend', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: '3d moon lamp personalized',
    popularity: 95,
  },
  {
    id: 'wooden-photo-frame-husband-birthday-004',
    name: 'Personalised Wooden Photo Frame Collage for Husband Birthday (297 x 210 mm)',
    slug: 'personalised-wooden-photo-frame-husband',
    description: 'A beautifully crafted A4 size wooden photo frame collage to celebrate your husband\'s special day. A timeless keepsake.',
    price: 1030,
    category: 'photo-frames',
    occasion: ['birthday', 'fathers-day', 'anniversary'],
    recipient: ['husband', 'father', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden photo collage frame',
    popularity: 88,
  },
  {
    id: 'custom-acrylic-desk-name-plate-005',
    name: 'Custom Acrylic Desk Name Plate (25 x 7 cm)',
    slug: 'custom-acrylic-desk-name-plate',
    description: 'A sleek and professional custom acrylic desk name plate. The perfect corporate gift for promotions, new jobs, or office decor.',
    price: 699,
    category: 'corporate-utility-name-plates',
    occasion: ['corporate-event', 'corporate-welcome-kits'],
    recipient: ['colleagues', 'boss', 'employee'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'acrylic desk nameplate',
    popularity: 80,
  },
  {
    id: 'assorted-chocolate-hamper-006',
    name: 'Assorted Chocolate Hamper (12 Pieces)',
    slug: 'assorted-chocolate-hamper-12-pieces',
    description: 'A delicious assortment of 12 premium chocolates, beautifully packaged in a gift hamper for any sweet occasion.',
    price: 999,
    category: 'chocolates',
    occasion: ['birthday', 'anniversary', 'valentines-day', 'party'],
    recipient: ['friends', 'family', 'women', 'men', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'chocolate gift hamper',
    popularity: 91,
    trending: true,
  },
  {
    id: 'engraved-wooden-bottle-opener-007',
    name: 'Custom Engraved Wooden Bottle Opener (Magnetic, 10 x 5 cm)',
    slug: 'custom-engraved-wooden-bottle-opener',
    description: 'A stylish and practical magnetic wooden bottle opener, custom engraved for a personal touch. Great for any home bar.',
    price: 349,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'fathers-day', 'diwali-bhaidooj'],
    recipient: ['father', 'men', 'friends', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden bottle opener',
    popularity: 78,
  },
  {
    id: 'spotify-code-plaque-acrylic-008',
    name: 'Spotify Code Plaque (Acrylic, 20 x 10 cm)',
    slug: 'spotify-code-plaque-acrylic',
    description: 'Capture your special song with a custom Spotify code plaque. A modern and sentimental gift for music lovers.',
    price: 1499,
    category: 'spotify-gifts',
    occasion: ['birthday', 'anniversary', 'valentines-day'],
    recipient: ['music-lovers', 'couples', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'spotify music plaque',
    popularity: 94,
  },
  {
    id: 'personalised-mug-mother-birthday-009',
    name: 'Personalised Mug for Mother Birthday (11 oz)',
    slug: 'personalised-mug-mother-birthday',
    description: 'Show your love for mom with a personalized 11oz ceramic mug, perfect for her morning coffee or tea.',
    price: 299,
    category: 'utility-mugs',
    occasion: ['birthday', 'mothers-day', 'anniversary'],
    recipient: ['mother', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'mother birthday mug',
    popularity: 86,
  },
  {
    id: 'magnetic-glass-photo-frame-010',
    name: 'Magnetic Glass Photo Frame (4 x 6 in)',
    slug: 'magnetic-glass-photo-frame-4x6',
    description: 'A modern and elegant magnetic glass photo frame to display your favorite memories. Perfect for desks and shelves.',
    price: 699,
    category: 'photo-frames',
    occasion: ['graduation', 'house-warming', 'farewell'],
    recipient: ['student', 'employee', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'glass photo frame',
    popularity: 82,
  },
  {
    id: 'framed-bobblehead-single-011',
    name: 'Framed Bobblehead (Single Person, 15 cm)',
    slug: 'framed-bobblehead-single-15cm',
    description: 'A unique and humorous framed bobblehead, custom-made to resemble a single person. A gift that guarantees a smile.',
    price: 2799,
    category: 'mini-you-framed-bobbleheads',
    occasion: ['birthday', 'fathers-day', 'anniversary', 'farewell'],
    recipient: ['father', 'husband', 'colleagues', 'boss'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'custom framed bobblehead',
    popularity: 89,
    trending: true,
  },
  {
    id: 'wooden-plaque-engraved-quote-012',
    name: 'Wooden Plaque with Engraved Quote (20 x 10 cm)',
    slug: 'wooden-plaque-engraved-quote',
    description: 'An inspiring wooden plaque with a custom engraved quote. A thoughtful gift for motivation and encouragement.',
    price: 499,
    category: 'wooden-gifts',
    occasion: ['graduation', 'house-warming', 'corporate-event'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'engraved wooden plaque',
    popularity: 77,
  },
  {
    id: 'photo-collage-canvas-12x18-013',
    name: 'Photo Collage Canvas (12″ x 18″)',
    slug: 'photo-collage-canvas-12x18',
    description: 'Turn your favorite photos into a stunning piece of wall art with this 12x18 inch photo collage canvas.',
    price: 1499,
    category: 'photo-collage',
    occasion: ['anniversary', 'valentines-day', 'birthday', 'wedding'],
    recipient: ['couples', 'family', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'canvas photo collage',
    popularity: 93,
  },
  {
    id: 'custom-photo-book-album-014',
    name: 'Custom Photo Book Album (Hardcover, 30 Pages)',
    slug: 'custom-photo-book-album-hardcover',
    description: 'Create a beautiful hardcover photo album with 30 pages to preserve your most cherished memories from weddings, travels, or family events.',
    price: 1699,
    category: 'photobook-album',
    occasion: ['wedding', 'anniversary', 'graduation', 'birthday'],
    recipient: ['couples', 'family', 'student'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'hardcover photo album',
    popularity: 87,
  },
  {
    id: 'heart-shaped-resin-art-frame-015',
    name: 'Heart-Shaped Resin Art Photo Frame (6″)',
    slug: 'heart-shaped-resin-art-photo-frame',
    description: 'A beautiful 6-inch heart-shaped photo frame made with custom resin art, perfect for a romantic and artistic gift.',
    price: 1099,
    category: 'resin-art',
    occasion: ['valentines-day', 'anniversary', 'birthday'],
    recipient: ['girlfriend', 'wife', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'resin art heart frame',
    popularity: 90,
  },
  {
    id: 'wooden-gifts-combo-016',
    name: 'Wooden Gifts Combo: Bottle + Pen + Diary',
    slug: 'wooden-gifts-combo-bottle-pen-diary',
    description: 'An elegant wooden gift combo featuring a bottle, a pen, and a diary. Ideal for corporate gifting or as a premium personal gift.',
    price: 1299,
    category: 'gift-hampers',
    occasion: ['corporate-event', 'house-warming', 'graduation'],
    recipient: ['colleagues', 'boss', 'student'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden gift set',
    popularity: 85,
  },
  {
    id: 'photo-to-art-digital-sketch-017',
    name: 'Photo to Art Digital Sketch (A4)',
    slug: 'photo-to-art-digital-sketch-a4',
    description: 'Transform your favorite photo into a beautiful A4 size digital sketch. A unique and personal piece of art.',
    price: 999,
    category: 'photo-gifts-general',
    occasion: ['birthday', 'anniversary', 'farewell'],
    recipient: ['family', 'friends', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'digital photo sketch',
    popularity: 84,
  },
  {
    id: 'stone-tiles-photo-frame-mosaic-018',
    name: 'Stone & Tiles Photo Frame (Mosaic, 6 x 6 in)',
    slug: 'stone-tiles-photo-frame-mosaic',
    description: 'A unique photo frame made with a beautiful mosaic of stone and tiles. A rustic and artistic addition to any home.',
    price: 1299,
    category: 'photo-frames',
    occasion: ['house-warming', 'anniversary', 'wedding'],
    recipient: ['couples', 'homeowner', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'mosaic tile frame',
    popularity: 79,
  },
  {
    id: 'custom-magic-mug-color-changing-019',
    name: 'Custom Mugs (Magic Color-Changing, 11 oz)',
    slug: 'custom-magic-mug-color-changing',
    description: 'Surprise someone with a heat-activated magic mug! Your custom photo appears when a hot beverage is poured in.',
    price: 399,
    category: 'utility-mugs',
    occasion: ['birthday', 'mothers-day', 'fathers-day', 'friendship-day'],
    recipient: ['family', 'friends', 'colleagues'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'magic color changing mug',
    popularity: 93,
    trending: true,
  },
  {
    id: 'personalized-photo-tile-set-020',
    name: 'Personalized Photo Tile Set (4 Tiles, 4 x 4 in)',
    slug: 'personalized-photo-tile-set-4-tiles',
    description: 'Create a unique wall display with a set of 4 personalized 4x4 inch photo tiles. Modern, versatile, and easy to arrange.',
    price: 799,
    category: 'photo-tiles',
    occasion: ['house-warming', 'anniversary', 'family'],
    recipient: ['homeowner', 'couples', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'custom photo tiles',
    popularity: 83,
  },
  {
    id: 'led-backlit-photo-frame-021',
    name: 'Custom LED Backlit Photo Frame (8 x 10 in)',
    slug: 'custom-led-backlit-photo-frame',
    description: 'Illuminate your cherished memories with this stunning 8x10 inch LED backlit photo frame. A modern and eye-catching decor piece.',
    price: 1899,
    category: 'photo-frames',
    occasion: ['anniversary', 'house-warming', 'birthday', 'wedding'],
    recipient: ['couples', 'family', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'led light photo frame',
    popularity: 91,
    trending: true,
  },
  {
    id: 'magnetic-floating-glass-frame-022',
    name: 'Magnetic Floating Glass Frame (5 x 7 in)',
    slug: 'magnetic-floating-glass-frame-5x7',
    description: 'A chic and modern 5x7 inch magnetic floating glass frame that makes your photos stand out. Perfect for any decor style.',
    price: 899,
    category: 'photo-frames',
    occasion: ['graduation', 'farewell', 'house-warming', 'birthday'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'floating glass frame',
    popularity: 85,
  },
  {
    id: 'heart-shaped-collage-frame-023',
    name: 'Heart-Shaped Collage Photo Frame (5 x 7 in slots)',
    slug: 'heart-shaped-collage-photo-frame',
    description: 'Display a collection of your favorite moments in this lovely heart-shaped collage frame with multiple 5x7 inch slots.',
    price: 1299,
    category: 'photo-collage',
    occasion: ['valentines-day', 'anniversary', 'wedding'],
    recipient: ['couples', 'girlfriend', 'wife'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'heart collage frame',
    popularity: 88,
  },
  {
    id: 'triptych-canvas-photo-frame-024',
    name: 'Triptych Canvas Photo Frame (12 x 24 in)',
    slug: 'triptych-canvas-photo-frame-12x24',
    description: 'Create a dramatic wall display with a triptych canvas, splitting one beautiful image across three 12x24 inch panels.',
    price: 2499,
    category: 'home-decor',
    occasion: ['house-warming', 'wedding', 'anniversary'],
    recipient: ['homeowner', 'couples', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'triptych canvas wall art',
    popularity: 86,
  },
  {
    id: 'personalised-bamboo-photo-frame-025',
    name: 'Personalised Bamboo Photo Frame (6 x 8 in)',
    slug: 'personalised-bamboo-photo-frame',
    description: 'An eco-friendly and stylish 6x8 inch bamboo photo frame, personalized with your photo and text for a natural touch.',
    price: 949,
    category: 'photo-frames',
    occasion: ['birthday', 'mothers-day', 'house-warming'],
    recipient: ['mother', 'women', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'bamboo photo frame',
    popularity: 81,
  },
  {
    id: 'chevron-pattern-wood-frame-026',
    name: 'Chevron-Pattern Wood Photo Frame (8 x 10 in)',
    slug: 'chevron-pattern-wood-photo-frame',
    description: 'A trendy 8x10 inch wooden photo frame featuring a modern chevron pattern, perfect for contemporary home decor.',
    price: 1299,
    category: 'photo-frames',
    occasion: ['anniversary', 'house-warming', 'wedding'],
    recipient: ['couples', 'homeowner', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'chevron wood frame',
    popularity: 79,
  },
  {
    id: 'mdf-collage-frame-027',
    name: 'MDF Collage Frame (10 x 12 in, 5 slots)',
    slug: 'mdf-collage-frame-10x12',
    description: 'A versatile 10x12 inch MDF collage frame with 5 slots to showcase a collection of memories from school, college, or work.',
    price: 1349,
    category: 'photo-collage',
    occasion: ['graduation', 'farewell', 'friendship-day'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'collage frame mdf',
    popularity: 80,
  },
  {
    id: 'rustic-log-slice-photo-frame-028',
    name: 'Rustic Log Slice Photo Frame (6 x 8 in)',
    slug: 'rustic-log-slice-photo-frame',
    description: 'Bring the outdoors in with this charming 6x8 inch rustic photo frame made from a real log slice. Perfect for a cozy home.',
    price: 1199,
    category: 'photo-frames',
    occasion: ['house-warming', 'diwali-bhaidooj', 'birthday'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'log slice frame',
    popularity: 84,
  },
  {
    id: 'shabby-chic-white-frame-029',
    name: 'Shabby Chic White Frame (8 x 8 in)',
    slug: 'shabby-chic-white-frame-8x8',
    description: 'An elegant 8x8 inch shabby chic white frame, perfect for wedding photos or as a lovely gift for a baby shower.',
    price: 749,
    category: 'photo-frames',
    occasion: ['wedding', 'baby-shower', 'anniversary'],
    recipient: ['new-parents', 'couples', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'white shabby chic frame',
    popularity: 78,
  },
  {
    id: 'black-glossy-metal-frame-030',
    name: 'Black Glossy Metal Frame (8 x 10 in)',
    slug: 'black-glossy-metal-frame-8x10',
    description: 'A sophisticated and sleek 8x10 inch black glossy metal frame, ideal for corporate gifts or recognizing professional achievements.',
    price: 799,
    category: 'photo-frames',
    occasion: ['corporate-event', 'farewell'],
    recipient: ['employee', 'colleagues', 'boss'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'black metal frame',
    popularity: 82,
  },
  {
    id: 'resin-flower-photo-frame-031',
    name: 'Resin Embedded Flower Photo Frame (7 x 9 in)',
    slug: 'resin-embedded-flower-photo-frame',
    description: 'A breathtaking 7x9 inch photo frame with real flowers embedded in crystal-clear resin. A truly romantic and unique gift.',
    price: 1399,
    category: 'resin-art',
    occasion: ['anniversary', 'valentines-day', 'wedding'],
    recipient: ['couples', 'women', 'girlfriend', 'wife'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'resin flower frame',
    popularity: 92,
    trending: true,
  },
  {
    id: 'floating-box-photo-frame-032',
    name: 'Floating Box Photo Frame (8 x 10 in)',
    slug: 'floating-box-photo-frame-8x10',
    description: 'An 8x10 inch floating box frame that creates a stunning 3D effect for your photos. A modern centerpiece for any room.',
    price: 1299,
    category: 'photo-frames',
    occasion: ['birthday', 'house-warming', 'anniversary'],
    recipient: ['friends', 'family', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: '3d box frame',
    popularity: 85,
  },
  {
    id: 'metal-clip-multi-photo-frame-033',
    name: 'Metal Clip Multi-Photo Frame (4×6 in each, Set of 4)',
    slug: 'metal-clip-multi-photo-frame',
    description: 'A versatile multi-photo display featuring metal clips to hold four 4x6 inch photos. Perfect for a casual and modern look.',
    price: 999,
    category: 'photo-frames',
    occasion: ['graduation', 'farewell', 'friendship-day'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'clip photo display',
    popularity: 83,
  },
  {
    id: 'photo-frame-with-led-clock-034',
    name: 'Photo Frame with LED Clock (6×8 in)',
    slug: 'photo-frame-with-led-clock',
    description: 'A multifunctional 6x8 inch photo frame that also features a bright LED clock. A perfect blend of sentiment and utility.',
    price: 1599,
    category: 'photo-clocks',
    occasion: ['corporate-event', 'house-warming', 'farewell'],
    recipient: ['colleagues', 'homeowner', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo frame clock',
    popularity: 88,
  },
  {
    id: 'floating-photo-frame-with-shelves-035',
    name: 'Floating Photo Frame with Shelves (10×12 in)',
    slug: 'floating-photo-frame-with-shelves',
    description: 'This innovative 10x12 inch floating photo frame includes small shelves, perfect for displaying trinkets alongside your photo.',
    price: 2199,
    category: 'photo-frames',
    occasion: ['house-warming', 'diwali-bhaidooj', 'birthday'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'shelf photo frame',
    popularity: 86,
  },
  {
    id: 'geometric-acrylic-photo-frame-036',
    name: 'Geometric Acrylic Photo Frame (7×7 in)',
    slug: 'geometric-acrylic-photo-frame',
    description: 'A modern 7x7 inch photo frame with a striking geometric acrylic design. Ideal for contemporary decor.',
    price: 1099,
    category: 'photo-frames',
    occasion: ['birthday', 'anniversary', 'house-warming'],
    recipient: ['couples', 'friends', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'geometric acrylic frame',
    popularity: 80,
  },
  {
    id: 'reclaimed-wood-photo-frame-037',
    name: 'Reclaimed Wood Photo Frame (8×10 in)',
    slug: 'reclaimed-wood-photo-frame',
    description: 'An eco-friendly 8x10 inch photo frame made from reclaimed wood, offering a unique rustic charm for any home.',
    price: 1599,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'birthday', 'anniversary'],
    recipient: ['homeowner', 'family', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'reclaimed wood frame',
    popularity: 84,
  },
  {
    id: 'photo-frame-with-built-in-vase-038',
    name: 'Photo Frame with Built-In Vase (5×7 in)',
    slug: 'photo-frame-with-built-in-vase',
    description: 'A beautiful 5x7 inch photo frame combined with a small vase for a fresh flower. A thoughtful and romantic gift.',
    price: 1799,
    category: 'photo-frames',
    occasion: ['mothers-day', 'valentines-day', 'anniversary'],
    recipient: ['mother', 'wife', 'girlfriend'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'vase photo frame',
    popularity: 89,
  },
  {
    id: 'round-bamboo-photo-frame-039',
    name: 'Round Bamboo Photo Frame (ø 8 in)',
    slug: 'round-bamboo-photo-frame-8-inch',
    description: 'A unique 8-inch round photo frame made from sustainable bamboo, perfect for a natural and minimalist aesthetic.',
    price: 1099,
    category: 'photo-frames',
    occasion: ['anniversary', 'wedding', 'house-warming'],
    recipient: ['couples', 'homeowner', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'round bamboo frame',
    popularity: 82,
  },
  {
    id: 'personalised-photo-frame-spotify-code-040',
    name: 'Personalised Photo Frame with Spotify Code (6×6 in)',
    slug: 'personalised-photo-frame-spotify-code',
    description: 'Combine a favorite photo with a special song in this 6x6 inch frame featuring a scannable Spotify code.',
    price: 1499,
    category: 'spotify-gifts',
    occasion: ['birthday', 'valentines-day', 'anniversary'],
    recipient: ['music-lovers', 'couples', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'spotify code frame',
    popularity: 95,
    trending: true,
  },
  {
    id: 'laser-cut-metal-photo-frame-041',
    name: 'Laser-Cut Metal Photo Frame (6×6 in)',
    slug: 'laser-cut-metal-photo-frame',
    description: 'An intricately laser-cut 6x6 inch metal photo frame that adds an industrial-chic touch to any desk or shelf.',
    price: 1099,
    category: 'photo-frames',
    occasion: ['graduation', 'corporate-event', 'farewell'],
    recipient: ['student', 'employee', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'laser cut metal frame',
    popularity: 78,
  },
  {
    id: 'pivot-double-sided-photo-frame-042',
    name: 'Pivot Double-Sided Photo Frame (6×8 in)',
    slug: 'pivot-double-sided-photo-frame',
    description: 'Display two memories at once with this clever 6x8 inch double-sided pivoting photo frame. Perfect for a desk or mantelpiece.',
    price: 1899,
    category: 'photo-frames',
    occasion: ['anniversary', 'house-warming', 'birthday'],
    recipient: ['couples', 'family', 'parents-day'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'double sided frame',
    popularity: 87,
  },
  {
    id: 'collage-frame-in-heart-shape-043',
    name: 'Collage Frame in Heart Shape (13 slots)',
    slug: 'collage-frame-heart-shape-13-slots',
    description: 'A large, heart-shaped collage frame with 13 slots to create a beautiful mosaic of your most treasured moments.',
    price: 1499,
    category: 'photo-collage',
    occasion: ['valentines-day', 'anniversary', 'wedding'],
    recipient: ['couples', 'family', 'girlfriend', 'wife'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'large heart collage',
    popularity: 90,
  },
  {
    id: 'floating-glass-frame-led-accent-044',
    name: 'Floating Glass Frame with LED Accent (5×7 in)',
    slug: 'floating-glass-frame-led-accent',
    description: 'This 5x7 inch floating glass frame is enhanced with a subtle LED accent, making your photo glow beautifully.',
    price: 1699,
    category: 'photo-frames',
    occasion: ['birthday', 'farewell', 'anniversary'],
    recipient: ['friends', 'colleagues', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'led glass frame',
    popularity: 88,
  },
  {
    id: 'reclaimed-wood-inset-photo-frame-045',
    name: 'Reclaimed Wood Inset Photo Frame (8×10 in)',
    slug: 'reclaimed-wood-inset-photo-frame',
    description: 'An 8x10 inch photo frame featuring a photo inset within a solid block of beautiful, eco-friendly reclaimed wood.',
    price: 1599,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'birthday', 'fathers-day'],
    recipient: ['homeowner', 'men', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'inset wood frame',
    popularity: 85,
  },
  {
    id: 'staggered-wood-panel-frame-046',
    name: 'Staggered Wood Panel Frame (4×6 in each)',
    slug: 'staggered-wood-panel-frame',
    description: 'A unique wall piece with staggered wooden panels, each holding a 4x6 inch photo, creating a rustic, multi-dimensional display.',
    price: 1399,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'birthday', 'family'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wood panel frame',
    popularity: 83,
  },
  {
    id: 'personalised-double-sided-pivot-frame-047',
    name: 'Personalised Double-Sided Pivot Frame (6×8 in)',
    slug: 'personalised-double-sided-pivot-frame',
    description: 'A 6x8 inch pivoting frame that holds two photos back-to-back, personalized with engraved text for an extra special touch.',
    price: 1899,
    category: 'photo-frames',
    occasion: ['anniversary', 'wedding', 'valentines-day'],
    recipient: ['couples', 'newlyweds', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'personalized pivot frame',
    popularity: 87,
  },
  {
    id: 'rustic-pallet-wood-photo-frame-048',
    name: 'Rustic Pallet Wood Photo Frame (12×12 in)',
    slug: 'rustic-pallet-wood-photo-frame',
    description: 'A large 12x12 inch photo frame crafted from rustic pallet wood, perfect for adding a touch of farmhouse charm to your home.',
    price: 2299,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'diwali-bhaidooj', 'family'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'pallet wood frame',
    popularity: 86,
  },
  {
    id: 'photo-frame-with-keepsake-drawer-049',
    name: 'Photo Frame with Keepsake Drawer (8×10 in)',
    slug: 'photo-frame-with-keepsake-drawer',
    description: 'This clever 8x10 inch photo frame features a small built-in drawer, perfect for storing tiny keepsakes and mementos.',
    price: 2199,
    category: 'photo-frames',
    occasion: ['birthday', 'anniversary', 'new-baby'],
    recipient: ['couples', 'parents-day', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'keepsake box frame',
    popularity: 89,
  },
  {
    id: 'stained-glass-mosaic-photo-frame-050',
    name: 'Stained Glass Mosaic Photo Frame (6×6 in)',
    slug: 'stained-glass-mosaic-photo-frame',
    description: 'A vibrant 6x6 inch photo frame adorned with a colorful stained glass mosaic. A true piece of art for your cherished photos.',
    price: 2499,
    category: 'photo-frames',
    occasion: ['wedding', 'house-warming', 'anniversary'],
    recipient: ['couples', 'women', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'stained glass frame',
    popularity: 88,
  },
  {
    id: 'photo-frame-with-watch-storage-051',
    name: 'Photo Frame with Watch Storage (6×8 in)',
    slug: 'photo-frame-with-watch-storage',
    description: 'A unique gift for him, this 6x8 inch photo frame includes a compartment for storing a watch. Functional and sentimental.',
    price: 1999,
    category: 'photo-frames',
    occasion: ['fathers-day', 'birthday', 'anniversary'],
    recipient: ['father', 'husband', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'watch storage frame',
    popularity: 85,
  },
  {
    id: 'copper-plated-metal-photo-frame-052',
    name: 'Copper-Plated Metal Photo Frame (8×10 in)',
    slug: 'copper-plated-metal-photo-frame',
    description: 'An elegant 8x10 inch metal photo frame with a warm copper-plated finish. Ideal for professional settings or stylish homes.',
    price: 1499,
    category: 'photo-frames',
    occasion: ['graduation', 'corporate-event', 'anniversary'],
    recipient: ['student', 'employee', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'copper metal frame',
    popularity: 82,
  },
  {
    id: 'photo-frame-with-candle-holder-053',
    name: 'Photo Frame with Candle Holder (6×8 in)',
    slug: 'photo-frame-with-candle-holder',
    description: 'Create a romantic ambiance with this 6x8 inch photo frame that features an integrated candle holder.',
    price: 1499,
    category: 'photo-frames',
    occasion: ['anniversary', 'valentines-day', 'wedding'],
    recipient: ['couples', 'wife', 'girlfriend'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'candle holder frame',
    popularity: 89,
  },
  {
    id: 'multi-color-mosaic-tile-frame-054',
    name: 'Multi-Color Mosaic Tile Frame (6×6 in)',
    slug: 'multi-color-mosaic-tile-frame',
    description: 'A vibrant and artistic 6x6 inch photo frame made with a cheerful multi-color mosaic of tiles. Perfect for a splash of color.',
    price: 1299,
    category: 'photo-tiles',
    occasion: ['house-warming', 'diwali-bhaidooj', 'birthday'],
    recipient: ['homeowner', 'women', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'colorful mosaic frame',
    popularity: 84,
  },
  {
    id: 'genogram-family-tree-frame-055',
    name: 'Genogram Family Tree Frame (12×16 in)',
    slug: 'genogram-family-tree-frame',
    description: 'Celebrate your heritage with this large 12x16 inch family tree frame, designed to showcase multiple generations.',
    price: 2499,
    category: 'photo-frames',
    occasion: ['anniversary', 'family', 'parents-day', 'grandparents-day'],
    recipient: ['family', 'parents-day'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'family tree frame',
    popularity: 91,
  },
  {
    id: 'metallic-floating-frame-set-of-2-056',
    name: 'Metallic Floating Frame Set of 2 (8×10 in)',
    slug: 'metallic-floating-frame-set-of-2',
    description: 'A stylish set of two 8x10 inch metallic floating frames, perfect for creating a cohesive and modern gallery wall.',
    price: 2199,
    category: 'photo-frames',
    occasion: ['house-warming', 'wedding', 'anniversary'],
    recipient: ['couples', 'homeowner', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'set of floating frames',
    popularity: 87,
  },
  {
    id: 'personalized-engraved-glass-frame-057',
    name: 'Personalized Engraved Glass Frame (6×8 in)',
    slug: 'personalized-engraved-glass-frame',
    description: 'An elegant 6x8 inch glass photo frame, personalized with custom engraving for a timeless and sophisticated gift.',
    price: 1699,
    category: 'photo-frames',
    occasion: ['anniversary', 'birthday', 'wedding', 'valentines-day'],
    recipient: ['couples', 'family', 'parents-day'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'engraved glass frame',
    popularity: 90,
  },
  {
    id: 'framed-canvas-photo-print-058',
    name: 'Framed Canvas Photo Print (10×12 in)',
    slug: 'framed-canvas-photo-print-10x12',
    description: 'Your photo printed on high-quality canvas and elegantly framed. This 10x12 inch piece is ready to hang wall art.',
    price: 1799,
    category: 'home-decor',
    occasion: ['house-warming', 'wedding', 'anniversary'],
    recipient: ['homeowner', 'couples', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'framed canvas print',
    popularity: 88,
  },
  {
    id: 'layered-wood-inset-frame-059',
    name: 'Layered Wood Inset Frame (8×10 in)',
    slug: 'layered-wood-inset-frame-8x10',
    description: 'This 8x10 inch frame features a unique layered wood design, creating depth and a rustic aesthetic for your photo.',
    price: 1599,
    category: 'wooden-gifts',
    occasion: ['anniversary', 'birthday', 'house-warming'],
    recipient: ['friends', 'family', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'layered wood frame',
    popularity: 84,
  },
  {
    id: 'led-light-up-floating-frame-060',
    name: 'LED Light-Up Floating Frame (7×9 in)',
    slug: 'led-light-up-floating-frame',
    description: 'A mesmerizing 7x9 inch floating frame that lights up with LEDs, making your photo the center of attention.',
    price: 2099,
    category: 'photo-frames',
    occasion: ['birthday', 'farewell', 'anniversary', 'party'],
    recipient: ['colleagues', 'friends', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'light up frame',
    popularity: 92,
    trending: true,
  },
  {
    id: 'rustic-twine-wrapped-photo-frame-061',
    name: 'Rustic Twine-Wrapped Photo Frame (5×7 in)',
    slug: 'rustic-twine-wrapped-photo-frame',
    description: 'A charming 5x7 inch photo frame wrapped in rustic twine, perfect for a coastal, bohemian, or farmhouse decor style.',
    price: 849,
    category: 'photo-frames',
    occasion: ['house-warming', 'diwali-bhaidooj', 'birthday'],
    recipient: ['friends', 'family', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'twine photo frame',
    popularity: 79,
  },
  {
    id: 'concrete-look-resin-photo-frame-062',
    name: 'Concrete-Look Resin Photo Frame (6×8 in)',
    slug: 'concrete-look-resin-photo-frame',
    description: 'Achieve a modern, industrial look with this 6x8 inch photo frame made from resin with a realistic concrete finish.',
    price: 1299,
    category: 'resin-art',
    occasion: ['house-warming', 'corporate-event', 'farewell'],
    recipient: ['employee', 'men', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'concrete resin frame',
    popularity: 81,
  },
  {
    id: 'cross-stitched-fabric-photo-frame-063',
    name: 'Cross-Stitched Fabric Photo Frame (5×7 in)',
    slug: 'cross-stitched-fabric-photo-frame',
    description: 'A cozy and handmade-feel 5x7 inch photo frame featuring a beautiful cross-stitched fabric border.',
    price: 899,
    category: 'photo-frames',
    occasion: ['wedding', 'baby-shower', 'mothers-day'],
    recipient: ['couples', 'new-parents', 'mother', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'fabric photo frame',
    popularity: 78,
  },
  {
    id: 'floating-glass-block-frame-064',
    name: 'Floating Glass Block Frame (5×7 in)',
    slug: 'floating-glass-block-frame',
    description: 'Your 5x7 photo appears to float inside a solid, elegant block of clear glass. A minimalist and modern statement piece.',
    price: 1199,
    category: 'photo-frames',
    occasion: ['birthday', 'anniversary', 'wedding'],
    recipient: ['friends', 'couples', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'glass block frame',
    popularity: 86,
  },
  {
    id: 'engraved-marble-photo-frame-065',
    name: 'Engraved Marble Photo Frame (5×7 in)',
    slug: 'engraved-marble-photo-frame',
    description: 'A luxurious 5x7 inch photo frame crafted from real marble and custom engraved for a premium, lasting gift.',
    price: 1699,
    category: 'photo-frames',
    occasion: ['graduation', 'corporate-event', 'wedding'],
    recipient: ['student', 'employee', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'marble photo frame',
    popularity: 89,
  },
  {
    id: 'leather-wrapped-photo-frame-066',
    name: 'Leather-Wrapped Photo Frame (8×10 in)',
    slug: 'leather-wrapped-photo-frame',
    description: 'A sophisticated 8x10 inch photo frame wrapped in high-quality leather, perfect for an executive desk or a classic study.',
    price: 1499,
    category: 'photo-frames',
    occasion: ['anniversary', 'valentines-day', 'fathers-day'],
    recipient: ['couples', 'husband', 'father', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'leather photo frame',
    popularity: 87,
  },
  {
    id: 'photo-frame-with-miniature-display-box-067',
    name: 'Photo Frame with Miniature Display Box (7×9 in)',
    slug: 'photo-frame-with-miniature-display-box',
    description: 'This unique 7x9 inch photo frame includes a small display box to showcase a cherished miniature or collectible alongside a photo.',
    price: 1799,
    category: 'shadow-box',
    occasion: ['birthday', 'house-warming', 'family'],
    recipient: ['family', 'men', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'miniature display frame',
    popularity: 85,
  },
  {
    id: 'round-metal-frame-with-stand-068',
    name: 'Round Metal Frame with Stand (6×6 in)',
    slug: 'round-metal-frame-with-stand',
    description: 'A chic 6x6 inch round metal photo frame with an integrated stand, perfect for a modern office or home.',
    price: 1299,
    category: 'photo-frames',
    occasion: ['corporate-event', 'farewell', 'graduation'],
    recipient: ['employee', 'colleagues', 'student'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'round metal frame',
    popularity: 82,
  },
  {
    id: 'rustic-pallet-collage-frame-069',
    name: 'Rustic Pallet Collage Frame (12×12 in, 4 slots)',
    slug: 'rustic-pallet-collage-frame',
    description: 'A large 12x12 inch collage frame made from rustic pallet wood, with 4 slots to create a beautiful family photo display.',
    price: 2399,
    category: 'photo-collage',
    occasion: ['house-warming', 'family', 'anniversary'],
    recipient: ['family', 'homeowner', 'parents-day'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'pallet collage frame',
    popularity: 88,
  },
  {
    id: 'photo-frame-with-shelving-ledge-070',
    name: 'Photo Frame with Shelving Ledge (8×10 in)',
    slug: 'photo-frame-with-shelving-ledge',
    description: 'An 8x10 inch photo frame that features a top ledge, providing a small shelf space for decor or keys.',
    price: 2099,
    category: 'photo-frames',
    occasion: ['house-warming', 'diwali-bhaidooj', 'birthday'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'ledge shelf frame',
    popularity: 86,
  },
  {
    id: 'photo-tile-magnet-pack-071',
    name: 'Personalized Photo Tile Magnet (Pack of 6)',
    slug: 'personalized-photo-tile-magnet-pack',
    description: 'A fun pack of 6 personalized photo tile magnets. Perfect for decorating your fridge or any magnetic surface with memories.',
    price: 449,
    category: 'photo-tiles',
    occasion: ['house-warming', 'graduation', 'friendship-day'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo tile magnets',
    popularity: 90,
    trending: true,
  },
  {
    id: 'floating-acrylic-frame-keychain-072',
    name: 'Floating Acrylic Frame Keychain (Custom Photo)',
    slug: 'floating-acrylic-frame-keychain',
    description: 'Carry your favorite photo with you everywhere with this stylish floating acrylic frame keychain.',
    price: 299,
    category: 'utility-keychains',
    occasion: ['birthday', 'farewell', 'friendship-day'],
    recipient: ['friends', 'family', 'student'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo keychain acrylic',
    popularity: 85,
  },
  {
    id: 'custom-metal-print-clock-073',
    name: 'Custom Metal Print Clock (20×20 cm)',
    slug: 'custom-metal-print-clock',
    description: 'A modern 20x20 cm clock with your photo printed directly on a metal surface. A stunning and functional piece of art.',
    price: 2299,
    category: 'photo-clocks',
    occasion: ['corporate-event', 'house-warming', 'anniversary'],
    recipient: ['employee', 'homeowner', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'metal photo clock',
    popularity: 87,
  },
  {
    id: 'geo-pattern-wooden-collage-frame-074',
    name: 'Geo-Pattern Wooden Collage Frame (10×12 in, 6 slots)',
    slug: 'geo-pattern-wooden-collage-frame',
    description: 'A stylish 10x12 inch wooden collage frame featuring a modern geometric pattern and 6 slots for your photos.',
    price: 1699,
    category: 'photo-collage',
    occasion: ['anniversary', 'wedding', 'house-warming'],
    recipient: ['couples', 'newlyweds', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'geometric wood collage',
    popularity: 84,
  },
  {
    id: 'photo-frame-with-floating-shelves-075',
    name: 'Photo Frame with Floating Shelves (12×12 in)',
    slug: 'photo-frame-with-floating-shelves',
    description: 'A large 12x12 inch photo frame integrated with floating shelves, creating a unique wall display for photos and decor.',
    price: 2599,
    category: 'photo-frames',
    occasion: ['house-warming', 'diwali-bhaidooj', 'family'],
    recipient: ['friends', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'frame with shelves',
    popularity: 88,
  },
  {
    id: 'personalized-soundwave-wooden-plaque-076',
    name: 'Personalized Soundwave Wooden Plaque (30×10 cm)',
    slug: 'personalized-soundwave-wooden-plaque',
    description: 'Capture a voice message or a favorite song as a soundwave, beautifully engraved on a 30x10 cm wooden plaque.',
    price: 1299,
    category: 'wooden-gifts',
    occasion: ['anniversary', 'valentines-day', 'birthday'],
    recipient: ['music-lovers', 'couples', 'husband', 'wife'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'soundwave art wood',
    popularity: 94,
  },
  {
    id: 'floating-resin-art-photo-block-077',
    name: 'Floating Resin Art Photo Block (8×6 in)',
    slug: 'floating-resin-art-photo-block',
    description: 'Your 8x6 photo appears to float within a stunning block of custom resin art. A true conversation starter.',
    price: 1399,
    category: 'resin-art',
    occasion: ['valentines-day', 'birthday', 'anniversary'],
    recipient: ['couples', 'friends', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'resin photo block',
    popularity: 91,
  },
  {
    id: 'personalized-acrylic-photo-block-078',
    name: 'Personalized Acrylic Photo Block (5×5×2 cm)',
    slug: 'personalized-acrylic-photo-block',
    description: 'A thick, high-quality 5x5 cm acrylic block that gives your photo a vibrant, 3D effect. Perfect for desks.',
    price: 999,
    category: 'photo-gifts-general',
    occasion: ['graduation', 'farewell', 'corporate-event'],
    recipient: ['student', 'colleagues', 'employee'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'acrylic photo block',
    popularity: 87,
  },
  {
    id: 'custom-photo-collage-wall-clock-079',
    name: 'Custom Photo Collage Wall Clock (10×10 in)',
    slug: 'custom-photo-collage-wall-clock',
    description: 'Tell time with your memories. This 10x10 inch wall clock features a custom photo collage around the face.',
    price: 2099,
    category: 'photo-clocks',
    occasion: ['anniversary', 'house-warming', 'family'],
    recipient: ['couples', 'homeowner', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo collage clock',
    popularity: 89,
  },
  {
    id: 'engraved-wooden-usb-drive-080',
    name: 'Engraved Wooden USB Drive (32 GB)',
    slug: 'engraved-wooden-usb-drive-32gb',
    description: 'A functional 32GB USB drive encased in wood, personalized with an engraving. A classy tech gift.',
    price: 899,
    category: 'wooden-gifts',
    occasion: ['graduation', 'corporate-event', 'farewell'],
    recipient: ['student', 'employee', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden usb drive',
    popularity: 83,
  },
  {
    id: 'personalized-corkboard-photo-frame-081',
    name: 'Personalized Corkboard Photo Frame (12×12 in)',
    slug: 'personalized-corkboard-photo-frame',
    description: 'A 12x12 inch frame with a corkboard center, perfect for pinning photos, notes, and mementos. Great for an office or study.',
    price: 1199,
    category: 'photo-frames',
    occasion: ['corporate-event', 'house-warming', 'graduation'],
    recipient: ['student', 'colleagues', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'corkboard photo frame',
    popularity: 82,
  },
  {
    id: 'floating-magazine-style-photo-frame-082',
    name: 'Floating Magazine-Style Photo Frame (8×10 in)',
    slug: 'floating-magazine-style-photo-frame',
    description: 'Frame your photo like a magazine cover with this stylish 8x10 inch floating frame, complete with customizable text.',
    price: 1499,
    category: 'photo-frames',
    occasion: ['house-warming', 'wedding', 'birthday'],
    recipient: ['couples', 'homeowner', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'magazine cover frame',
    popularity: 88,
  },
  {
    id: 'personalized-resin-paperweight-083',
    name: 'Personalized Resin Paperweight (8×8 cm)',
    slug: 'personalized-resin-paperweight',
    description: 'An elegant 8x8 cm resin paperweight, personalized with a name or logo. A premium gift for any professional.',
    price: 649,
    category: 'resin-art',
    occasion: ['corporate-event', 'farewell'],
    recipient: ['employee', 'boss', 'colleagues'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'resin paperweight',
    popularity: 80,
  },
  {
    id: 'custom-wooden-coat-hook-084',
    name: 'Custom Wooden Coat Hook (Set of 3)',
    slug: 'custom-wooden-coat-hook-set-of-3',
    description: 'A set of 3 stylish wooden coat hooks, personalized with names or initials. A functional and decorative gift.',
    price: 899,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'diwali-bhaidooj', 'wedding'],
    recipient: ['friends', 'family', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden coat hooks',
    popularity: 83,
  },
  {
    id: 'photo-frame-with-chalkboard-insert-085',
    name: 'Photo Frame with Chalkboard Insert (6×8 in)',
    slug: 'photo-frame-with-chalkboard-insert',
    description: 'A versatile 6x8 inch photo frame that includes a chalkboard insert for messages, menus, or doodles.',
    price: 1249,
    category: 'photo-frames',
    occasion: ['house-warming', 'wedding', 'family'],
    recipient: ['couples', 'family', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'chalkboard photo frame',
    popularity: 85,
  },
  {
    id: 'personalized-floating-multi-use-frame-086',
    name: 'Personalized Floating Multi-Use Frame (8×10 in)',
    slug: 'personalized-floating-multi-use-frame',
    description: 'An 8x10 inch personalized floating frame designed for multiple uses, from photos to displaying art or certificates.',
    price: 2099,
    category: 'photo-frames',
    occasion: ['house-warming', 'anniversary', 'graduation'],
    recipient: ['friends', 'family', 'student'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'multi use frame',
    popularity: 87,
  },
  {
    id: 'custom-wooden-puzzle-photo-frame-087',
    name: 'Custom Wooden Puzzle Photo Frame (300 Pieces)',
    slug: 'custom-wooden-puzzle-photo-frame',
    description: 'Turn your photo into a 300-piece wooden puzzle that can be assembled and then displayed in its own frame. A fun, interactive gift.',
    price: 1299,
    category: 'wooden-gifts',
    occasion: ['birthday', 'family', 'anniversary'],
    recipient: ['family', 'kids-boys', 'kids-girls', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo puzzle wood',
    popularity: 91,
  },
  {
    id: 'personalized-glass-block-photo-lamp-088',
    name: 'Personalized Glass Block Photo Lamp (10×10×10 cm)',
    slug: 'personalized-glass-block-photo-lamp',
    description: 'A stunning 10cm cube glass block, personalized with your photo and lit from within to create a magical glowing lamp.',
    price: 1299,
    category: 'photo-lamps',
    occasion: ['anniversary', 'valentines-day', 'wedding'],
    recipient: ['couples', 'wife', 'girlfriend'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'glass block lamp',
    popularity: 90,
  },
  {
    id: 'custom-floating-hexagon-frame-089',
    name: 'Custom Floating Hexagon Frame (6×6 in)',
    slug: 'custom-floating-hexagon-frame',
    description: 'A modern and trendy 6x6 inch floating hexagon frame, perfect for creating a honeycomb-style gallery wall.',
    price: 1199,
    category: 'photo-frames',
    occasion: ['house-warming', 'birthday', 'friendship-day'],
    recipient: ['friends', 'women', 'homeowner'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'hexagon photo frame',
    popularity: 84,
  },
  {
    id: 'personalised-wooden-name-puzzle-kids-090',
    name: 'Personalised Wooden Name Puzzle (Kids)',
    slug: 'personalised-wooden-name-puzzle-kids',
    description: 'A fun and educational wooden puzzle, personalized with a child\'s name. Helps with letter recognition and motor skills.',
    price: 1099,
    category: 'wooden-gifts',
    occasion: ['birthday', 'baby-shower', 'childrens-day'],
    recipient: ['kids-boys', 'kids-girls', 'new-parents'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'wooden name puzzle',
    popularity: 89,
  },
  {
    id: 'led-bluetooth-speaker-photo-frame-091',
    name: 'Custom LED Bluetooth Speaker Photo Frame (8×10 in)',
    slug: 'custom-led-bluetooth-speaker-photo-frame',
    description: 'The ultimate multi-functional gift: an 8x10 inch photo frame with built-in LED lights and a Bluetooth speaker.',
    price: 2499,
    category: 'tech-gadgets',
    occasion: ['birthday', 'house-warming', 'party'],
    recipient: ['music-lovers', 'friends', 'men', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'speaker photo frame',
    popularity: 93,
    trending: true,
  },
  {
    id: 'personalized-photo-tile-coaster-set-092',
    name: 'Personalized Photo Tile Coaster Set (4 Tiles)',
    slug: 'personalized-photo-tile-coaster-set',
    description: 'Protect your surfaces in style with a set of 4 personalized photo tile coasters. A great housewarming or family gift.',
    price: 599,
    category: 'photo-tiles',
    occasion: ['house-warming', 'diwali-bhaidooj', 'wedding'],
    recipient: ['friends', 'family', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo coasters set',
    popularity: 86,
  },
  {
    id: 'custom-floating-acrylic-nameplate-desk-093',
    name: 'Custom Floating Acrylic Nameplate (Desk)',
    slug: 'custom-floating-acrylic-nameplate-desk',
    description: 'A premium desk nameplate where the text appears to float within a block of clear acrylic. A very modern corporate gift.',
    price: 699,
    category: 'corporate-utility-name-plates',
    occasion: ['corporate-event', 'farewell'],
    recipient: ['employee', 'boss', 'colleagues'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'floating acrylic nameplate',
    popularity: 83,
  },
  {
    id: 'personalized-resin-art-phone-stand-094',
    name: 'Personalized Resin Art Phone Stand',
    slug: 'personalized-resin-art-phone-stand',
    description: 'A unique and artistic phone stand made from personalized resin art. A stylish and functional desk accessory.',
    price: 799,
    category: 'resin-art',
    occasion: ['birthday', 'graduation', 'friendship-day'],
    recipient: ['student', 'friends', 'women', 'men'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'resin phone stand',
    popularity: 88,
  },
  {
    id: 'custom-photo-collage-laptop-skin-095',
    name: 'Custom Photo Collage Laptop Skin',
    slug: 'custom-photo-collage-laptop-skin',
    description: 'Personalize your laptop with a custom skin featuring a collage of your favorite photos. Protects and adds personality.',
    price: 899,
    category: 'photo-collage',
    occasion: ['graduation', 'birthday', 'farewell'],
    recipient: ['student', 'friends', 'colleagues'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'laptop skin collage',
    popularity: 85,
  },
  {
    id: 'engraved-wooden-cutting-board-096',
    name: 'Engraved Wooden Cutting Board (30×20 cm)',
    slug: 'engraved-wooden-cutting-board',
    description: 'A beautiful and functional 30x20 cm wooden cutting board, personalized with an engraving. A perfect kitchen gift.',
    price: 899,
    category: 'wooden-gifts',
    occasion: ['house-warming', 'wedding', 'anniversary'],
    recipient: ['couples', 'homeowner', 'family', 'women'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'engraved cutting board',
    popularity: 87,
  },
  {
    id: 'personalized-photo-yoga-mat-097',
    name: 'Personalized Photo Yoga Mat',
    slug: 'personalized-photo-yoga-mat',
    description: 'Find your zen on a yoga mat personalized with your own photo or design. A unique gift for fitness lovers.',
    price: 1499,
    category: 'sports-fitness',
    occasion: ['birthday', 'new-year', 'party'],
    recipient: ['women', 'friends', 'family'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'custom yoga mat',
    popularity: 80,
  },
  {
    id: 'custom-caricature-on-canvas-098',
    name: 'Custom Caricature on Canvas (24×36 in)',
    slug: 'custom-caricature-on-canvas',
    description: 'A large and impressive 24x36 inch canvas print of a custom caricature. A fun and memorable centerpiece for any celebration.',
    price: 2999,
    category: 'mini-you-caricatures',
    occasion: ['birthday', 'farewell', 'wedding'],
    recipient: ['colleagues', 'friends', 'family', 'couples'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'caricature canvas print',
    popularity: 91,
  },
  {
    id: 'personalized-photo-travel-tumbler-099',
    name: 'Personalized Photo Travel Tumbler (500 ml)',
    slug: 'personalized-photo-travel-tumbler',
    description: 'A 500ml stainless steel travel tumbler personalized with your photo. Keeps drinks hot or cold on the go.',
    price: 899,
    category: 'drinkware',
    occasion: ['graduation', 'farewell', 'birthday'],
    recipient: ['student', 'colleagues', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'photo travel tumbler',
    popularity: 86,
  },
  {
    id: 'floating-led-resin-art-block-100',
    name: 'Floating LED Resin Art Block (10×10×5 cm)',
    slug: 'floating-led-resin-art-block',
    description: 'A mesmerizing 10x10x5 cm resin art block with embedded objects that appear to float, illuminated by internal LEDs.',
    price: 1499,
    category: 'resin-art',
    occasion: ['birthday', 'valentines-day', 'anniversary'],
    recipient: ['couples', 'women', 'friends'],
    imageUrls: ['https://placehold.co/600x800.png'],
    dataAiHint: 'led resin art block',
    popularity: 92,
    trending: true,
  },
];


export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(product => product.slug === slug);
}
