
import type { Occasion, GiftType, Recipient, Product, Category } from './types';
import {
  Gift, Shirt, Smartphone, HomeIcon as HomeIconLucide, ToyBrick, Gem, Users, ShoppingBag,
  MapPin, HelpCircle, Briefcase, Percent, Star, User, Heart,
  Cake, CalendarDays, Camera, Car, Crown, Drama, Feather, Flag, Flower, Gamepad,
  Globe, GraduationCap, HandHeart, History, Lamp, Leaf, Medal, Moon,
  Mountain, Music, Newspaper, Package, Palette, PartyPopper, Pencil,
  Pin, Plane, Puzzle, Rocket, School, Search, Shield, Smile, Sparkles as SparklesIcon,
  Sprout, Store, Sun, Tag, ThumbsUp, Ticket, TreeDeciduous, Trophy,
  Utensils, Wand, Watch, Wind, Wine, Zap, Anchor, Award, Baby,
} from 'lucide-react';

export const OCCASIONS_LIST: Occasion[] = [
  // Personal
  { id: 'birthday', name: 'Birthday', slug: 'birthday', Icon: PartyPopper, dataAiHint: "birthday party" },
  { id: 'anniversary', name: 'Anniversary', slug: 'anniversary', Icon: Gift, dataAiHint: "anniversary celebration" },
  { id: 'wedding', name: 'Wedding', slug: 'wedding', Icon: Users, dataAiHint: "wedding ceremony" },
  { id: 'farewell', name: 'Farewell', slug: 'farewell', Icon: Plane, dataAiHint: "farewell party plane" },
  { id: 'house-warming', name: 'House Warming', slug: 'house-warming', Icon: HomeIconLucide, dataAiHint: "new home gift" },
  { id: 'baby-shower', name: 'Baby Shower', slug: 'baby-shower', Icon: Baby, dataAiHint: "baby shower gift" },
  // Special Days
  { id: 'fathers-day', name: "Father's Day", slug: 'fathers-day', Icon: Trophy, dataAiHint: "father child trophy" },
  { id: 'valentines-day', name: "Valentine's Day", slug: 'valentines-day', Icon: Heart, dataAiHint: "valentine romance" },
  { id: 'mothers-day', name: "Mother's Day", slug: 'mothers-day', Icon: Star, dataAiHint: "mother child star" },
  { id: 'womens-day', name: "Women's Day", slug: 'womens-day', Icon: Award, dataAiHint: "women empowerment award" },
  { id: 'brothers-day', name: "Brother's Day", slug: 'brothers-day', Icon: Shield, dataAiHint: "brother shield bond" },
  { id: 'parents-day', name: "Parents' Day", slug: 'parents-day', Icon: Users, dataAiHint: "happy family parents" },
  { id: 'friendship-day', name: "Friendship Day", slug: 'friendship-day', Icon: HandHeart, dataAiHint: "friends handshake" },
  { id: 'teachers-day', name: "Teacher's Day", slug: 'teachers-day', Icon: GraduationCap, dataAiHint: "teacher student book" },
  { id: 'childrens-day', name: "Children's Day", slug: 'childrens-day', Icon: Smile, dataAiHint: "happy children playing" },
  { id: 'new-year', name: 'New Year', slug: 'new-year', Icon: PartyPopper, dataAiHint: "new year fireworks" },
  { id: 'grandparents-day', name: "Grandparents' Day", slug: 'grandparents-day', Icon: Users, dataAiHint: "elderly couple love" },
  // Festivals
  { id: 'rakhi', name: 'Rakhi', slug: 'rakhi', Icon: Gift, dataAiHint: "rakhi thread festival" },
  { id: 'durga-puja', name: 'Durga Puja', slug: 'durga-puja', Icon: Drama, dataAiHint: "durga idol pandal" },
  { id: 'karva-chauth', name: 'Karva Chauth', slug: 'karva-chauth', Icon: Moon, dataAiHint: "karva chauth ritual moon" },
  { id: 'diwali-bhaidooj', name: 'Diwali & Bhaidooj', slug: 'diwali-bhaidooj', Icon: Lamp, dataAiHint: "diwali lights diya" },
  { id: 'christmas', name: 'Christmas', slug: 'christmas', Icon: TreeDeciduous, dataAiHint: "christmas tree gifts" },
  { id: 'holi', name: 'Holi', slug: 'holi', Icon: Palette, dataAiHint: "holi colors festival" },
  { id: 'poila-baisakh', name: 'Poila Baisakh', slug: 'poila-baisakh', Icon: CalendarDays, dataAiHint: "bengali new year calendar" },
  { id: 'onam', name: 'Onam', slug: 'onam', Icon: Flower, dataAiHint: "onam pookalam festival" },
  { id: 'bihu', name: 'Bihu', slug: 'bihu', Icon: Music, dataAiHint: "bihu dance music" },
  // Corporate specific occasions can also be gift types
  { id: 'corporate-welcome-kits', name: 'Welcome Kits (Occasion)', slug: 'corporate-welcome-kits', Icon: Package, dataAiHint: "corporate welcome basket" },
  { id: 'corporate-memento-event', name: 'Memento Event', slug: 'corporate-memento-event', Icon: Award, dataAiHint: "event memento" },
  { id: 'corporate-awards-ceremony', name: 'Awards Ceremony', slug: 'corporate-awards-ceremony', Icon: Trophy, dataAiHint: "trophy awards night" },
];

export const GIFT_TYPES_LIST: GiftType[] = [
  { id: 'pebble-art', name: 'Pebble Art', slug: 'pebble-art', Icon: Gem, dataAiHint: "stone art craft" },
  { id: 'mini-you-series', name: 'Mini You Series', slug: 'mini-you-series', Icon: ToyBrick, dataAiHint: "3d miniature figure" },
  { id: '3d-crystals', name: '3D Crystals', slug: '3d-crystals', Icon: Gem, dataAiHint: "crystal engraving gift" },
  { id: 'photo-lamps', name: 'Photo Lamps', slug: 'photo-lamps', Icon: Lamp, dataAiHint: "custom 3d light" },
  { id: 'photo-gifts-general', name: 'Photo Gifts (General)', slug: 'photo-gifts-general', Icon: Gift, dataAiHint: "personalized photo present" },
  { id: 'photo-frames', name: 'Photo Frames', slug: 'photo-frames', Icon: Camera, dataAiHint: "picture frame decor" },
  { id: 'photobook-album', name: 'Photobook Album', slug: 'photobook-album', Icon: Newspaper, dataAiHint: "custom photo album" },
  { id: 'photo-clocks', name: 'Photo Clocks', slug: 'photo-clocks', Icon: Watch, dataAiHint: "wall clock custom" },
  { id: 'gift-hampers', name: 'Gift Hampers', slug: 'gift-hampers', Icon: Package, dataAiHint: "gift basket hamper" },
  { id: 'resin-art', name: 'Resin Art', slug: 'resin-art', Icon: Palette, dataAiHint: "epoxy resin craft" },
  { id: 'shadow-box', name: 'Shadow Box', slug: 'shadow-box', Icon: Package, dataAiHint: "3d shadow box frame" },
  { id: 'spotify-gifts', name: 'Spotify Gifts', slug: 'spotify-gifts', Icon: Music, dataAiHint: "spotify music plaque" },
  { id: 'heart-shaped-gifts', name: 'Heart Shaped Gifts', slug: 'heart-shaped-gifts', Icon: Heart, dataAiHint: "heart shape present" },
  { id: 'wooden-gifts', name: 'Wooden Gifts', slug: 'wooden-gifts', Icon: Shield, dataAiHint: "engraved wood item" },
  { id: 'chocolates', name: 'Chocolates', slug: 'chocolates', Icon: Gift, dataAiHint: "gourmet chocolate box" },

  { id: 'utility-mugs', name: 'Utility Gifts: Mugs', slug: 'utility-mugs', Icon: Utensils, dataAiHint: "custom coffee mug" },
  { id: 'utility-pens', name: 'Utility Gifts: Pens', slug: 'utility-pens', Icon: Pencil, dataAiHint: "engraved pen luxury" },
  { id: 'utility-t-shirts', name: 'Utility Gifts: T-Shirts', slug: 'utility-t-shirts', Icon: Shirt, dataAiHint: "custom printed tshirt" },
  { id: 'utility-bottles', name: 'Utility Gifts: Bottles', slug: 'utility-bottles', Icon: Package, dataAiHint: "personalized water bottle" },
  { id: 'utility-diaries', name: 'Utility Gifts: Diaries', slug: 'utility-diaries', Icon: Newspaper, dataAiHint: "custom journal diary" },
  { id: 'utility-keychains', name: 'Utility Gifts: Key Chains', slug: 'utility-keychains', Icon: Anchor, dataAiHint: "custom photo keychain" },

  { id: 'home-living-lamps', name: 'Home & Living: Lamps', slug: 'home-living-lamps', Icon: Lamp, dataAiHint: "decorative table lamp" }, // Could overlap photo-lamps
  { id: 'home-living-clocks', name: 'Home & Living: Clocks', slug: 'home-living-clocks', Icon: Watch, dataAiHint: "stylish wall clock" }, // Could overlap photo-clocks
  { id: 'home-living-cushions', name: 'Home & Living: Cushions', slug: 'home-living-cushions', Icon: ToyBrick, dataAiHint: "personalized photo cushion" },
  { id: 'home-living-bar-accessories', name: 'Home & Living: Bar Accessories', slug: 'home-living-bar-accessories', Icon: Wine, dataAiHint: "barware tools set" },
  { id: 'home-living-name-plates', name: 'Home & Living: Name Plates', slug: 'home-living-name-plates', Icon: Pin, dataAiHint: "custom door nameplate" },
  { id: 'home-living-magnets-tags', name: 'Home & Living: Magnets & Tags', slug: 'home-living-magnets-tags', Icon: Tag, dataAiHint: "fridge magnet custom" },

  // Mini You Series Sub-types
  { id: 'mini-you-bobbleheads', name: 'Mini You: Bobbleheads', slug: 'mini-you-bobbleheads', Icon: User, dataAiHint: "custom bobblehead doll" },
  { id: 'mini-you-caricatures', name: 'Mini You: Caricatures', slug: 'mini-you-caricatures', Icon: Smile, dataAiHint: "funny caricature art" },
  { id: 'mini-you-miniatures', name: 'Mini You: Full/Half Miniatures', slug: 'mini-you-miniatures', Icon: ToyBrick, dataAiHint: "3d selfie miniature" },
  { id: 'mini-you-framed-bobbleheads', name: 'Mini You: Framed Bobbleheads', slug: 'mini-you-framed-bobbleheads', Icon: User, dataAiHint: "bobblehead display case" },
  { id: 'mini-you-realistic-busts', name: 'Mini You: Realistic Busts', slug: 'mini-you-realistic-busts', Icon: User, dataAiHint: "custom bust statue" },


  // Corporate Gifts
  { id: 'corporate-awards', name: 'Corporate: Awards', slug: 'corporate-awards', Icon: Award, dataAiHint: "trophy plaque award" },
  { id: 'corporate-trophies', name: 'Corporate: Trophies', slug: 'corporate-trophies', Icon: Trophy, dataAiHint: "company trophy recognition" },
  { id: 'corporate-certificates', name: 'Corporate: Certificates', slug: 'corporate-certificates', Icon: Medal, dataAiHint: "achievement certificate frame" }, // Using Medal icon for variety
  { id: 'corporate-medals', name: 'Corporate: Medals', slug: 'corporate-medals', Icon: Medal, dataAiHint: "engraved medal award" },
  { id: 'corporate-mementos', name: 'Corporate: Mementos', slug: 'corporate-mementos', Icon: Gift, dataAiHint: "commemorative memento gift" },

  { id: 'corporate-apparel-tshirts', name: 'Corporate: T-Shirts', slug: 'corporate-apparel-tshirts', Icon: Shirt, dataAiHint: "branded company tshirt" },
  { id: 'corporate-apparel-caps', name: 'Corporate: Caps', slug: 'corporate-apparel-caps', Icon: Award, dataAiHint: "custom logo cap" }, // Using Award as a placeholder, could be specific cap icon if available
  { id: 'corporate-apparel-backpacks', name: 'Corporate: Backpacks', slug: 'corporate-apparel-backpacks', Icon: ShoppingBag, dataAiHint: "company logo backpack" },

  { id: 'corporate-joining-kits', name: 'Corporate: Joining Kits', slug: 'corporate-joining-kits', Icon: Package, dataAiHint: "employee welcome kit" },
  { id: 'corporate-joining-kits-2in1', name: 'Corporate: Joining Kits (2-in-1)', slug: 'corporate-joining-kits-2in1', Icon: Package, dataAiHint: "2in1 welcome set" },
  { id: 'corporate-joining-kits-3in1', name: 'Corporate: Joining Kits (3-in-1)', slug: 'corporate-joining-kits-3in1', Icon: Package, dataAiHint: "3in1 welcome set" },
  { id: 'corporate-joining-kits-4in1', name: 'Corporate: Joining Kits (4-in-1)', slug: 'corporate-joining-kits-4in1', Icon: Package, dataAiHint: "4in1 welcome set" },


  { id: 'corporate-stationery-stamps', name: 'Corporate: Rubber Stamps', slug: 'corporate-stationery-stamps', Icon: Pencil, dataAiHint: "company rubber stamp" },
  { id: 'corporate-stationery-pens', name: 'Corporate: Pens', slug: 'corporate-stationery-pens', Icon: Pencil, dataAiHint: "branded corporate pen" },
  { id: 'corporate-stationery-penstands', name: 'Corporate: Pen Stands', slug: 'corporate-stationery-penstands', Icon: Briefcase, dataAiHint: "desk pen holder" },
  { id: 'corporate-stationery-diaries', name: 'Corporate: Diaries', slug: 'corporate-stationery-diaries', Icon: Newspaper, dataAiHint: "custom logo diary" },
  { id: 'corporate-stationery-calendars', name: 'Corporate: Calendars', slug: 'corporate-stationery-calendars', Icon: CalendarDays, dataAiHint: "company desk calendar" },
  { id: 'corporate-stationery-cards', name: 'Corporate: ID & Visiting Cards', slug: 'corporate-stationery-cards', Icon: User, dataAiHint: "business visiting card" },

  { id: 'corporate-drinkware-bottles', name: 'Corporate: Bottles', slug: 'corporate-drinkware-bottles', Icon: Package, dataAiHint: "branded water bottle" },
  { id: 'corporate-drinkware-mugs', name: 'Corporate: Mugs', slug: 'corporate-drinkware-mugs', Icon: Utensils, dataAiHint: "company logo mug" },

  { id: 'corporate-utility-gift-sets', name: 'Corporate: Utility Gift Sets', slug: 'corporate-utility-gift-sets', Icon: Package, dataAiHint: "executive gift set" },
  { id: 'corporate-utility-desk-clocks', name: 'Corporate: Desk Clocks', slug: 'corporate-utility-desk-clocks', Icon: Watch, dataAiHint: "corporate desk clock" },
  { id: 'corporate-utility-desk-organizers', name: 'Corporate: Desk Organizers', slug: 'corporate-utility-desk-organizers', Icon: Briefcase, dataAiHint: "office desk organizer" },
  { id: 'corporate-utility-name-plates', name: 'Corporate: Name Plates', slug: 'corporate-utility-name-plates', Icon: Pin, dataAiHint: "desk name plate" },
  { id: 'corporate-utility-keychains', name: 'Corporate: Key Chains', slug: 'corporate-utility-keychains', Icon: Anchor, dataAiHint: "company logo keychain" },
  { id: 'corporate-utility-name-badges', name: 'Corporate: Name Badges', slug: 'corporate-utility-name-badges', Icon: User, dataAiHint: "employee name badge" },
];

export const RECIPIENTS_LIST: Recipient[] = [
  { id: 'men', name: 'Men (All)', slug: 'men', Icon: User, dataAiHint: "man silhouette" },
  { id: 'husband', name: 'Husband', slug: 'husband', Icon: Heart, dataAiHint: "loving couple husband" },
  { id: 'father', name: 'Father', slug: 'father', Icon: Award, dataAiHint: "father figure award" },
  { id: 'boyfriend', name: 'Boyfriend', slug: 'boyfriend', Icon: Rocket, dataAiHint: "romantic gift boyfriend" },
  { id: 'brother', name: 'Brother', slug: 'brother', Icon: Shield, dataAiHint: "siblings bond brother" },
  { id: 'son', name: 'Son', slug: 'son', Icon: GraduationCap, dataAiHint: "young boy son" },
  { id: 'male-friend', name: 'Male Friend', slug: 'male-friend', Icon: Users, dataAiHint: "friends group male" },
  { id: 'grandfather', name: 'Grandfather', slug: 'grandfather', Icon: User, dataAiHint: "elderly man grandfather" },
  { id: 'kids-boys', name: 'Kids (Boys)', slug: 'kids-boys', Icon: ToyBrick, dataAiHint: "playing boy child" },

  { id: 'women', name: 'Women (All)', slug: 'women', Icon: ShoppingBag, dataAiHint: "woman silhouette shopping" },
  { id: 'wife', name: 'Wife', slug: 'wife', Icon: Gem, dataAiHint: "happy couple wife" },
  { id: 'mother', name: 'Mother', slug: 'mother', Icon: Flower, dataAiHint: "motherly love flower" },
  { id: 'girlfriend', name: 'Girlfriend', slug: 'girlfriend', Icon: SparklesIcon, dataAiHint: "couple in love girlfriend" },
  { id: 'sister', name: 'Sister', slug: 'sister', Icon: Feather, dataAiHint: "sisters together feather" },
  { id: 'daughter', name: 'Daughter', slug: 'daughter', Icon: Star, dataAiHint: "young girl daughter" },
  { id: 'female-friend', name: 'Female Friend', slug: 'female-friend', Icon: Users, dataAiHint: "female friends group" },
  { id: 'grandmother', name: 'Grandmother', slug: 'grandmother', Icon: User, dataAiHint: "elderly woman grandmother" },
  { id: 'kids-girls', name: 'Kids (Girls)', slug: 'kids-girls', Icon: Smile, dataAiHint: "smiling girl child" },
  { id: 'couples', name: 'Couples', slug: 'couples', Icon: Users, dataAiHint: "romantic couple gift" },
  { id: 'winner', name: 'Winner', slug: 'winner', Icon: Trophy, dataAiHint: "trophy award winner" }, // Generic winner
  { id: 'employee', name: 'Employee', slug: 'employee', Icon: Briefcase, dataAiHint: "corporate employee gift"},
  { id: 'client', name: 'Client', slug: 'client', Icon: HandHeart, dataAiHint: "business client appreciation"},
];

export const CATEGORIES: Category[] = GIFT_TYPES_LIST.map(gt => ({...gt}));

export const PRODUCTS: Product[] = [
  // Personalised Mugs from prestogifts.com/personalised-photo-coffee-mugs
  {
    id: 'mug_child_birthday_001',
    name: 'Personalised Mug For Child Birthday',
    description: 'Brighten a child\'s birthday with this fun, personalized ceramic mug. Add their name and a cheerful design!',
    price: 300,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'child birthday mug',
    category: 'utility-mugs',
    occasion: ['birthday', 'childrens-day'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 75,
    trending: true, // "24 People are Looking at This"
    slug: 'personalised-mug-child-birthday',
    customizable: true,
    soldBy: 'Just4UGifts',
    attributes: [{ name: 'Material', value: 'Ceramic' }, { name: 'Capacity', value: '11oz' }],
    reviews: [{id: 'rev_mug_cb_1', author: 'Parent1', rating: 5, comment: 'My kid loved it!', date: '2023-01-10'}],
  },
  {
    id: 'mug_valentine_ceramic_002',
    name: 'Custom Printable Ceramic Mug For Valentine’s Day',
    description: 'Express your love with a custom ceramic mug this Valentine\'s Day. Features your special photo and message.',
    price: 299,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'valentine mug custom',
    category: 'utility-mugs',
    occasion: ['valentines-day'],
    recipient: ['husband', 'wife', 'boyfriend', 'girlfriend', 'couples'],
    popularity: 88, // "Sold 27 times in the Last 48 Hours"
    trending: true,
    slug: 'custom-ceramic-mug-valentines',
    customizable: true,
    soldBy: 'Just4UGifts',
    attributes: [{ name: 'Material', value: 'Ceramic' }, { name: 'Print', value: 'Custom Photo & Text' }],
  },
  {
    id: 'mug_birthday_daughter_003',
    name: 'Custom Printable Birthday Mugs For Daughter',
    description: 'A special birthday mug for your beloved daughter. Personalize with her photo and a sweet message.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'daughter birthday mug',
    category: 'utility-mugs',
    occasion: ['birthday'],
    recipient: ['daughter', 'kids-girls'],
    popularity: 80, // "68 People are Looking at This"
    trending: true,
    slug: 'custom-birthday-mug-daughter',
    customizable: true,
  },
  {
    id: 'mug_baby_monkey_handle_004',
    name: 'Customised Baby Mug with Monkey Handle (4.2″×3.2″)',
    description: 'Adorable baby mug with a fun monkey handle. Perfect for little hands. Customizable with baby\'s name or photo.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'baby mug monkey',
    category: 'utility-mugs',
    occasion: ['baby-shower', 'birthday'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 70,
    slug: 'custom-baby-mug-monkey-handle',
    customizable: true,
    attributes: [{name: 'Size', value: '4.2" x 3.2"'}, {name: 'Handle', value: 'Monkey Shape'}]
  },
  {
    id: 'mug_magic_best_friend_005',
    name: 'Custom Printable Magic Mug for Best Friend',
    description: 'Surprise your best friend with a magic mug! The image appears when hot liquid is poured in.',
    price: 699,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'magic mug friend',
    category: 'utility-mugs',
    occasion: ['birthday', 'friendship-day'],
    recipient: ['male-friend', 'female-friend'],
    popularity: 90, // "57 People are Looking at This"
    trending: true,
    slug: 'custom-magic-mug-best-friend',
    customizable: true,
    attributes: [{name: 'Feature', value: 'Heat Activated Image Reveal'}]
  },
  {
    id: 'mug_fathers_day_color_inside_006',
    name: 'Father’s Day Colour Inside Mug',
    description: 'Show dad how much you care with this special Father\'s Day mug featuring a colorful interior.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'father day mug color',
    category: 'utility-mugs',
    occasion: ['fathers-day'],
    recipient: ['father', 'men'],
    popularity: 78,
    slug: 'fathers-day-color-inside-mug',
    customizable: true,
  },
  {
    id: 'mug_photo_cow_handle_007',
    name: 'Personalised Photo Mug with Cow Handle (4.2″×3.2″)',
    description: 'A charming personalized mug with a unique cow-shaped handle. Great for kids or animal lovers.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'photo mug cow',
    category: 'utility-mugs',
    occasion: ['birthday'],
    recipient: ['kids-boys', 'kids-girls', 'women', 'men'],
    popularity: 72,
    reviews: [{id:'rev_mug_cow_1', author: 'Happy Parent', rating: 5, comment: 'So cute!', date: '2023-02-15'}],
    slug: 'personalised-photo-mug-cow-handle',
    customizable: true,
  },
  {
    id: 'mug_valentine_custom_008',
    name: 'Custom Printable Mugs For Valentine',
    description: 'Another lovely option for Valentine\'s Day, fully customizable with your photos and messages.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'valentine mug custom print',
    category: 'utility-mugs',
    occasion: ['valentines-day'],
    recipient: ['husband', 'wife', 'boyfriend', 'girlfriend', 'couples'],
    popularity: 85,
    slug: 'custom-printable-mugs-valentine',
    customizable: true,
  },
  {
    id: 'mug_dolphin_handle_kids_009',
    name: 'Exclusive Custom Mug with Dolphin Handle for Kids (4.2″×3.2″)',
    description: 'Make drinking fun with this exclusive dolphin handle mug, personalized for your child.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'kids mug dolphin',
    category: 'utility-mugs',
    occasion: ['birthday', 'childrens-day'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 68,
    slug: 'custom-mug-dolphin-handle-kids',
    customizable: true,
  },
  {
    id: 'mug_color_birthday_010',
    name: 'Custom Printed Colour Mug For Birthday',
    description: 'Celebrate a birthday with a vibrant, custom printed color mug. A cheerful gift for anyone.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'birthday mug color print',
    category: 'utility-mugs',
    occasion: ['birthday'],
    recipient: ['men', 'women', 'male-friend', 'female-friend'],
    popularity: 77,
    slug: 'custom-printed-color-mug-birthday',
    customizable: true,
  },
  {
    id: 'mug_conical_shape_011',
    name: 'Personalized Printable Conical Shape Mug',
    description: 'A stylish conical shaped mug that can be personalized with your unique design or photo.',
    price: 500,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'conical mug personalized',
    category: 'utility-mugs',
    occasion: ['birthday', 'anniversary', 'corporate-welcome-kits'],
    recipient: ['men', 'women', 'employee'],
    popularity: 70,
    slug: 'personalized-printable-conical-mug',
    customizable: true,
  },
  {
    id: 'mug_baby_tiger_handle_012',
    name: 'Customised Baby Mug with Tiger Handle for Kids (4.2″×3.2″)',
    description: 'Roar into fun with this customized baby mug featuring a playful tiger handle.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'baby mug tiger',
    category: 'utility-mugs',
    occasion: ['baby-shower', 'birthday'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 65,
    slug: 'customised-baby-mug-tiger-handle',
    customizable: true,
  },
  {
    id: 'mug_baby_picture_white_013',
    name: 'Personalized Baby Picture Printed White Mug',
    description: 'A classic white mug, personalized with an adorable baby picture. A heartwarming keepsake.',
    price: 280, // Assuming a price as it was not shown
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'baby picture mug',
    category: 'utility-mugs',
    occasion: ['baby-shower', 'grandparents-day'],
    recipient: ['mother', 'father', 'grandmother', 'grandfather'],
    popularity: 60,
    slug: 'personalized-baby-picture-white-mug',
    customizable: true,
  },

  // Top 10 Bestsellers from prestogifts.com
  {
    id: 'bestseller_moon_lamp_wife_001',
    name: 'Personalised 3D Moon Lamp for Wife Birthday (14cm,16 colours)',
    description: 'Enchanting LED moon lamp with custom photo wrap. A romantic and unique gift for birthdays and special occasions. Features 16 color options.',
    price: 2374.05,
    originalPrice: 2499,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'moon lamp custom',
    category: 'photo-lamps',
    occasion: ['birthday', 'anniversary', 'valentines-day'],
    recipient: ['wife', 'girlfriend', 'women'],
    popularity: 95,
    trending: true,
    slug: 'personalised-3d-moon-lamp-wife-birthday-14cm',
    customizable: true,
    attributes: [{ name: 'Size', value: '14cm Diameter' }, { name: 'Light Colors', value: '16 options with remote' }],
    reviews: [{ id: 'rev_moonlamp1', author: 'R. Sharma', rating: 4.6, comment: 'Magical gift, my wife adored it!', date: '2023-04-10' }],
    soldBy: 'Just4UGifts',
  },
  {
    id: 'bestseller_3d_crystal_husband_002',
    name: 'Personalised 3D Crystal Birthday Gift for Husband (50×80×50 mm)',
    description: 'Laser-etched 3D crystal keepsake with a personalized photo. A timeless and elegant gift for husbands.',
    price: 1835,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: '3d crystal husband',
    category: '3d-crystals',
    occasion: ['birthday', 'anniversary'],
    recipient: ['husband', 'men'],
    popularity: 92,
    trending: true,
    slug: 'personalised-3d-crystal-husband-birthday',
    customizable: true,
    attributes: [{ name: 'Dimensions', value: '50mm x 80mm x 50mm' }, {name: 'Material', value: 'K9 Crystal'}],
    reviews: [{ id: 'rev_3dcrystal1', author: 'P. Mehta', rating: 4.6, comment: 'Stunning quality and detail.', date: '2023-05-01' }],
  },
  {
    id: 'bestseller_mug_father_birthday_003',
    name: 'Personalised Mug for Father Birthday (11 oz)',
    description: 'Classic photo-printed ceramic mug to celebrate your father\'s birthday. A thoughtful and practical gift.',
    price: 299,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'father birthday mug print',
    category: 'utility-mugs',
    occasion: ['birthday', 'fathers-day'],
    recipient: ['father', 'men'],
    popularity: 98,
    trending: true,
    slug: 'personalised-mug-father-birthday-11oz',
    customizable: true,
    attributes: [{ name: 'Capacity', value: '11 oz' }, { name: 'Material', value: 'Ceramic' }],
    reviews: [{ id: 'rev_fathermug1', author: 'A. Kumar', rating: 4.9, comment: 'Dad loved his morning coffee in this!', date: '2023-06-10' }],
  },
  {
    id: 'bestseller_photo_frame_mother_004',
    name: 'Personalised Photo Frame for Mother Birthday (12″×12″)',
    description: 'Custom hardboard photo frame to display cherished memories. A perfect birthday gift for mothers.',
    price: 999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'mother birthday frame',
    category: 'photo-frames',
    occasion: ['birthday', 'mothers-day'],
    recipient: ['mother', 'women'],
    popularity: 90,
    trending: true,
    slug: 'personalised-photo-frame-mother-birthday-12x12',
    customizable: true,
    attributes: [{ name: 'Size', value: '12 inches x 12 inches' }, { name: 'Material', value: 'Hardboard' }],
    reviews: [{ id: 'rev_motherframe1', author: 'S. Patel', rating: 4.8, comment: 'Beautiful frame, excellent quality.', date: '2023-03-20' }],
  },
  {
    id: 'bestseller_wooden_slice_birthday_005',
    name: 'Exquisite Customised Wooden Slice For Birthday (16.51×17.78 cm)',
    description: 'Unique engraved wooden slice art. A rustic and charming personalized gift for birthdays.',
    price: 999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'wooden slice art',
    category: 'wooden-gifts',
    occasion: ['birthday', 'anniversary'],
    recipient: ['men', 'women', 'couples'],
    popularity: 88,
    trending: true,
    slug: 'customised-wooden-slice-birthday',
    customizable: true,
    attributes: [{ name: 'Dimensions', value: '16.51cm x 17.78cm' }, { name: 'Material', value: 'Natural Wood' }],
    reviews: [{ id: 'rev_woodslice1', author: 'K. Singh', rating: 4.7, comment: 'Very unique and well made.', date: '2023-07-05' }],
  },
  {
    id: 'bestseller_super_dad_frame_006',
    name: 'Personalized Super Dad Hardboard Photo Frame',
    description: 'Special Father’s Day photo frame to celebrate your super dad. A heartfelt gift.',
    price: 720,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'super dad frame',
    category: 'photo-frames',
    occasion: ['fathers-day', 'birthday'],
    recipient: ['father', 'men'],
    popularity: 85,
    trending: true,
    slug: 'personalized-super-dad-photo-frame',
    customizable: true,
    attributes: [{ name: 'Theme', value: 'Super Dad' }, {name: 'Material', value: 'Hardboard'}],
    reviews: [{ id: 'rev_superdadframe1', author: 'R. Gupta', rating: 4.2, comment: 'Dad was thrilled with this frame!', date: '2023-06-18' }],
  },
  {
    id: 'bestseller_moon_lamp_brother_007',
    name: 'Personalised 3D Moon Lamp for Brother Birthday (14cm,3 colours)',
    description: 'A smaller variant of the popular moon lamp, perfect for a brother\'s birthday. Features 3 color options.',
    price: 1999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'moon lamp brother',
    category: 'photo-lamps',
    occasion: ['birthday'],
    recipient: ['brother', 'men', 'kids-boys'],
    popularity: 89,
    trending: true,
    slug: 'personalised-3d-moon-lamp-brother-14cm-3color',
    customizable: true,
    attributes: [{ name: 'Size', value: '14cm Diameter' }, { name: 'Light Colors', value: '3 options' }],
    reviews: [{ id: 'rev_moonlampbro1', author: 'N. Iyer', rating: 4.8, comment: 'Cool gift for my brother!', date: '2023-08-11' }],
  },
  {
    id: 'bestseller_wall_clock_friend_008',
    name: 'Wall Clock Personalised for Male Friend Birthday (11″×11″)',
    description: 'Photo-printed wall clock, a practical and personalized birthday gift for a male friend.',
    price: 599,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'friend clock custom',
    category: 'photo-clocks',
    occasion: ['birthday', 'friendship-day'],
    recipient: ['male-friend', 'men'],
    popularity: 93,
    trending: true,
    slug: 'personalised-wall-clock-male-friend-birthday',
    customizable: true,
    attributes: [{ name: 'Size', value: '11 inches x 11 inches' }, { name: 'Type', value: 'Wall Clock' }],
    reviews: [{ id: 'rev_friendclock1', author: 'V. Reddy', rating: 5.0, comment: 'My friend loved it! Looks great.', date: '2023-02-25' }],
  },
  {
    id: 'bestseller_collage_frame_boys_009',
    name: 'Custom Photo Collage Frame Gift for Birthday of Boys & Friends',
    description: 'Multi-photo collage frame, perfect for capturing memories. Great for birthdays of boys and friends.',
    price: 999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'collage frame boys',
    category: 'photo-frames',
    occasion: ['birthday', 'friendship-day'],
    recipient: ['male-friend', 'kids-boys', 'men'],
    popularity: 91,
    trending: true,
    slug: 'custom-photo-collage-frame-boys-friends-birthday',
    customizable: true,
    attributes: [{ name: 'Style', value: 'Collage' }, {name: 'Material', value: 'Hardboard/Wood'}],
    reviews: [{ id: 'rev_collageboys1', author: 'S. Joshi', rating: 4.8, comment: 'Awesome way to display photos.', date: '2023-01-15' }],
  },
  {
    id: 'bestseller_fathers_day_mug_010',
    name: 'Father’s Day Special Coffee Mug',
    description: 'Themed coffee mug with "#1 Dad" print. A classic and appreciated Father\'s Day gift.',
    price: 350,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'dad mug father day',
    category: 'utility-mugs',
    occasion: ['fathers-day'],
    recipient: ['father', 'men'],
    popularity: 87,
    trending: true,
    slug: 'fathers-day-special-coffee-mug',
    customizable: false, // Pre-themed
    attributes: [{ name: 'Theme', value: '#1 Dad' }, {name: 'Material', value: 'Ceramic'}],
    reviews: [{ id: 'rev_dadmugspecial1', author: 'M. Khan', rating: 4.5, comment: 'Simple and sweet, dad liked it.', date: '2023-06-19' }],
  },

  // Additional varied products
  {
    id: 'mini_you_bobble_couple_001',
    name: 'Custom Couple Bobblehead Miniature',
    description: 'Get a hilarious and adorable custom bobblehead set for a couple. Perfect for anniversaries or weddings.',
    price: 3499,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'couple bobblehead custom',
    category: 'mini-you-bobbleheads',
    occasion: ['anniversary', 'wedding', 'valentines-day'],
    recipient: ['couples', 'husband', 'wife'],
    popularity: 85,
    trending: true,
    customizable: true,
    slug: 'custom-couple-bobblehead-miniature',
    attributes: [{name: 'Type', value: 'Couple Bobblehead'}],
  },
  {
    id: 'corporate_award_crystal_star_002',
    name: 'Star Performer Crystal Award',
    description: 'Elegant crystal star award for recognizing top employees or achievements. Engravable with custom text.',
    price: 2200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'crystal award star',
    category: 'corporate-awards',
    occasion: ['corporate-awards-ceremony'],
    recipient: ['employee', 'winner'],
    popularity: 80,
    customizable: true,
    slug: 'star-performer-crystal-award',
    attributes: [{name: 'Material', value: 'K9 Crystal'}, {name: 'Shape', value: 'Star'}],
  },
  {
    id: 'photo_frame_spotify_003',
    name: 'Personalized Spotify Music Plaque Frame',
    description: 'Capture a special song with a scannable Spotify code on a sleek acrylic plaque. Includes photo and song details.',
    price: 1299,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'spotify plaque custom',
    category: 'spotify-gifts',
    occasion: ['birthday', 'anniversary', 'valentines-day'],
    recipient: ['girlfriend', 'boyfriend', 'husband', 'wife', 'male-friend', 'female-friend'],
    popularity: 94,
    trending: true,
    customizable: true,
    slug: 'personalized-spotify-music-plaque-frame',
    attributes: [{name: 'Material', value: 'Acrylic'}, {name: 'Feature', value: 'Scannable Spotify Code'}],
  },
   {
    id: 'gift_hamper_gourmet_004',
    name: 'Gourmet Chocolate & Snacks Gift Hamper',
    description: 'A delightful hamper filled with premium chocolates, cookies, and savory snacks. Beautifully packaged for any occasion.',
    price: 2999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'gourmet gift hamper',
    category: 'gift-hampers',
    occasion: ['birthday', 'anniversary', 'new-year', 'corporate-utility-gift-sets'],
    recipient: ['men', 'women', 'couples', 'employee', 'client'],
    popularity: 82,
    giftWrapAvailable: true,
    slug: 'gourmet-chocolate-snacks-gift-hamper',
    attributes: [{name: 'Contents', value: 'Chocolates, Cookies, Nuts, Snacks'}]
  },
  {
    id: 'home_cushion_photo_005',
    name: 'Personalized Photo Cushion Cover',
    description: 'Add a personal touch to any room with a custom photo printed cushion cover. Soft and durable fabric.',
    price: 799,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'photo cushion custom',
    category: 'home-living-cushions',
    occasion: ['birthday', 'house-warming', 'mothers-day', 'anniversary'],
    recipient: ['mother', 'wife', 'girlfriend', 'grandmother', 'female-friend'],
    popularity: 78,
    customizable: true,
    slug: 'personalized-photo-cushion-cover',
    attributes: [{name: 'Material', value: 'Polyester Blend'}, {name: 'Size', value: '16x16 inches'}]
  },
  {
    id: 'corporate_joining_kit_premium_006',
    name: 'Premium Employee Joining Kit',
    description: 'Make new hires feel welcome with a premium joining kit. Includes a custom diary, pen, bottle, and keychain.',
    price: 2499,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'employee welcome kit',
    category: 'corporate-joining-kits-4in1',
    occasion: ['corporate-welcome-kits'],
    recipient: ['employee'],
    popularity: 88,
    customizable: true, // Items can be branded
    slug: 'premium-employee-joining-kit',
    attributes: [{name: 'Items', value: 'Diary, Pen, Bottle, Keychain'}]
  },
   {
    id: 'resin_art_coaster_set_007',
    name: 'Handmade Resin Art Coaster Set (Set of 4)',
    description: 'Beautiful and unique handmade resin art coasters. Each set is distinct with vibrant colors and patterns.',
    price: 1499,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'resin art coasters',
    category: 'resin-art',
    occasion: ['house-warming', 'wedding', 'birthday'],
    recipient: ['women', 'couples', 'female-friend'],
    popularity: 76,
    slug: 'handmade-resin-art-coaster-set',
    attributes: [{name: 'Material', value: 'Epoxy Resin'}, {name: 'Set', value: '4 Coasters'}]
  },
  {
    id: 'wooden_engraved_plaque_008',
    name: 'Personalized Engraved Wooden Plaque',
    description: 'A timeless gift, this wooden plaque can be engraved with a special message, quote, or name.',
    price: 1199,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'engraved wooden plaque',
    category: 'wooden-gifts',
    occasion: ['anniversary', 'farewell', 'birthday', 'corporate-memento-event'],
    recipient: ['men', 'women', 'father', 'mother', 'employee', 'teacher'],
    popularity: 83,
    customizable: true,
    slug: 'personalized-engraved-wooden-plaque',
    attributes: [{name: 'Material', value: 'Solid Wood'}, {name: 'Engraving', value: 'Custom Text/Logo'}]
  },
  {
    id: 'pebble_art_family_frame_009',
    name: 'Custom Pebble Art Family Frame',
    description: 'Adorable family portrait made with pebbles, framed beautifully. A unique and heartwarming gift.',
    price: 2100,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'pebble art family',
    category: 'pebble-art',
    occasion: ['house-warming', 'anniversary', 'parents-day', 'mothers-day', 'fathers-day'],
    recipient: ['family', 'parents', 'grandparents', 'mother', 'father'], // Assuming 'family', 'parents', 'grandparents' map to 'couples' or individual recipients
    popularity: 80,
    customizable: true,
    slug: 'custom-pebble-art-family-frame',
    attributes: [{name: 'Art Style', value: 'Pebble Art'}, {name: 'Theme', value: 'Family'}],
  },
  {
    id: 'mini_you_caricature_solo_010',
    name: 'Solo Digital Caricature from Photo',
    description: 'Get a fun, exaggerated digital caricature drawn from a photo. Perfect for profile pictures or social media.',
    price: 999,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'digital caricature solo',
    category: 'mini-you-caricatures',
    occasion: ['birthday', 'farewell', 'friendship-day'],
    recipient: ['men', 'women', 'male-friend', 'female-friend'],
    popularity: 79,
    customizable: true,
    slug: 'solo-digital-caricature-from-photo',
    attributes: [{name: 'Format', value: 'Digital File'}, {name: 'Style', value: 'Caricature'}],
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(product => product.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return PRODUCTS.filter(product => product.category === categorySlug);
}

export function getProductsByOccasion(occasionSlug: string): Product[] {
  return PRODUCTS.filter(product => product.occasion?.includes(occasionSlug));
}

export function getProductsByRecipient(recipientSlug: string): Product[] {
  return PRODUCTS.filter(product => product.recipient?.includes(recipientSlug));
}
