import type { Occasion, GiftType, Recipient, Product, Category } from './types';
import {
  Gift, Shirt, Smartphone, HomeIcon as HomeIconLucide, ToyBrick, Gem, Users, ShoppingBag, Cloud, Snowflake, Book,
  MapPin, HelpCircle, Briefcase, Percent, Star, User, Heart,
  Cake, CalendarDays, Camera, Car, Crown, Drama, Feather, Flag, Flower, Gamepad,
  Globe, GraduationCap, HandHeart, History, Lamp, Leaf, Medal, Moon,
  Mountain, Music, Newspaper, Package, Palette, PartyPopper, Pencil,
  Pin, Plane, Puzzle, Rocket, School, Search, Shield, Smile, Sparkles as SparklesIcon,
  Sprout, Store, Sun, Tag, ThumbsUp, Ticket, TreeDeciduous, Trophy,
  Utensils, Wand, Watch, Wind, Wine, Zap, Anchor, Award, Baby,
} from 'lucide-react';

export const OCCASIONS_LIST: Occasion[] = [
  // Personal
  { id: 'birthday', name: 'Birthday', slug: 'birthday', Icon: PartyPopper, dataAiHint: "birthday party" },
  { id: 'anniversary', name: 'Anniversary', slug: 'anniversary', Icon: Gift, dataAiHint: "anniversary celebration" },
  { id: 'wedding', name: 'Wedding', slug: 'wedding', Icon: Users, dataAiHint: "wedding ceremony" },
  { id: 'farewell', name: 'Farewell', slug: 'farewell', Icon: Plane, dataAiHint: "farewell party plane" },
  { id: 'house-warming', name: 'House Warming', slug: 'house-warming', Icon: HomeIconLucide, dataAiHint: "new home gift" },
  { id: 'baby-shower', name: 'Baby Shower', slug: 'baby-shower', Icon: Baby, dataAiHint: "baby shower gift" },
  // Special Days
  { id: 'fathers-day', name: "Father's Day", slug: 'fathers-day', Icon: Trophy, dataAiHint: "father child trophy" },
  { id: 'valentines-day', name: "Valentine's Day", slug: 'valentines-day', Icon: Heart, dataAiHint: "valentine romance" },
  { id: 'mothers-day', name: "Mother's Day", slug: 'mothers-day', Icon: Star, dataAiHint: "mother child star" },
  { id: 'womens-day', name: "Women's Day", slug: 'womens-day', Icon: Award, dataAiHint: "women empowerment award" },
  { id: 'brothers-day', name: "Brother's Day", slug: 'brothers-day', Icon: Shield, dataAiHint: "brother shield bond" },
  { id: 'parents-day', name: "Parents' Day", slug: 'parents-day', Icon: Users, dataAiHint: "happy family parents" },
  { id: 'friendship-day', name: "Friendship Day", slug: 'friendship-day', Icon: HandHeart, dataAiHint: "friends handshake" },
  { id: 'teachers-day', name: "Teacher's Day", slug: 'teachers-day', Icon: GraduationCap, dataAiHint: "teacher student book" },
  { id: 'childrens-day', name: "Children's Day", slug: 'childrens-day', Icon: Smile, dataAiHint: "happy children playing" },
  { id: 'new-year', name: 'New Year', slug: 'new-year', Icon: PartyPopper, dataAiHint: "new year fireworks" },
  { id: 'grandparents-day', name: "Grandparents' Day", slug: 'grandparents-day', Icon: Users, dataAiHint: "elderly couple love" },
  // Festivals
  { id: 'rakhi', name: 'Rakhi', slug: 'rakhi', Icon: Gift, dataAiHint: "rakhi thread festival" },
  { id: 'durga-puja', name: 'Durga Puja', slug: 'durga-puja', Icon: Drama, dataAiHint: "durga idol pandal" },
  { id: 'karva-chauth', name: 'Karva Chauth', slug: 'karva-chauth', Icon: Moon, dataAiHint: "karva chauth ritual moon" },
  { id: 'diwali-bhaidooj', name: 'Diwali & Bhaidooj', slug: 'diwali-bhaidooj', Icon: Lamp, dataAiHint: "diwali lights diya" },
  { id: 'christmas', name: 'Christmas', slug: 'christmas', Icon: TreeDeciduous, dataAiHint: "christmas tree gifts" },
  { id: 'holi', name: 'Holi', slug: 'holi', Icon: Palette, dataAiHint: "holi colors festival" },
  { id: 'poila-baisakh', name: 'Poila Baisakh', slug: 'poila-baisakh', Icon: CalendarDays, dataAiHint: "bengali new year calendar" },
  { id: 'onam', name: 'Onam', slug: 'onam', Icon: Flower, dataAiHint: "onam pookalam festival" },
  { id: 'bihu', name: 'Bihu', slug: 'bihu', Icon: Music, dataAiHint: "bihu dance music" },
  // Corporate specific occasions can also be gift types
  { id: 'corporate-welcome-kits', name: 'Welcome Kits (Occasion)', slug: 'corporate-welcome-kits', Icon: Package, dataAiHint: "corporate welcome basket" },
  { id: 'corporate-memento-event', name: 'Memento Event', slug: 'corporate-memento-event', Icon: Award, dataAiHint: "event memento" },
  { id: 'corporate-awards-ceremony', name: 'Awards Ceremony', slug: 'corporate-awards-ceremony', Icon: Trophy, dataAiHint: "trophy awards night" },
  { id: 'party', name: 'Party', slug: 'party', Icon: PartyPopper, dataAiHint: "celebration party" },
  { id: 'monsoon', name: 'Monsoon', slug: 'monsoon', Icon: Cloud, dataAiHint: "rainy season gift" }, // Assuming Cloud icon for Monsoon
  { id: 'winter', name: 'Winter', slug: 'winter', Icon: Snowflake, dataAiHint: "winter season gift" }, // Assuming Snowflake icon for Winter
  { id: 'sports-event', name: 'Sports Event', slug: 'sports-event', Icon: Gamepad, dataAiHint: "sports competition gift" },
  { id: 'spring', name: 'Spring', slug: 'spring', Icon: Sprout, dataAiHint: "spring season gift" },
  { id: 'summer', name: 'Summer', slug: 'summer', Icon: Sun, dataAiHint: "summer season gift" },
  { id: 'corporate-event', name: 'Corporate Event', slug: 'corporate-event', Icon: Briefcase, dataAiHint: "business event gift" },
  { id: 'trade-show', name: 'Trade Show', slug: 'trade-show', Icon: Briefcase, dataAiHint: "trade show giveaway" },
  { id: 'conference', name: 'Conference', slug: 'conference', Icon: Briefcase, dataAiHint: "conference gift" },
  { id: 'pet-birthday', name: 'Pet Birthday', slug: 'pet-birthday', Icon: Smile, dataAiHint: "pet birthday gift" },
  { id: 'new-pet', name: 'New Pet', slug: 'new-pet', Icon: Smile, dataAiHint: "new pet gift" },
  { id: 'honeymoon', name: 'Honeymoon', slug: 'honeymoon', Icon: Heart, dataAiHint: "honeymoon gift" },
  { id: 'dinner-party', name: 'Dinner Party', slug: 'dinner-party', Icon: Utensils, dataAiHint: "dinner party gift" },
];

export const GIFT_TYPES_LIST: GiftType[] = [
  { id: 'pebble-art', name: 'Pebble Art', slug: 'pebble-art', Icon: Gem, dataAiHint: "stone art craft" },
  { id: 'mini-you-series', name: 'Mini You Series', slug: 'mini-you-series', Icon: ToyBrick, dataAiHint: "3d miniature figure" },
  { id: '3d-crystals', name: '3D Crystals', slug: '3d-crystals', Icon: Gem, dataAiHint: "crystal engraving gift" },
  { id: 'photo-lamps', name: 'Photo Lamps', slug: 'photo-lamps', Icon: Lamp, dataAiHint: "custom 3d light" },
  { id: 'photo-gifts-general', name: 'Photo Gifts (General)', slug: 'photo-gifts-general', Icon: Gift, dataAiHint: "personalized photo present" },
  { id: 'photo-frames', name: 'Photo Frames', slug: 'photo-frames', Icon: Camera, dataAiHint: "picture frame decor" },
  { id: 'photobook-album', name: 'Photobook Album', slug: 'photobook-album', Icon: Newspaper, dataAiHint: "custom photo album" },
  { id: 'photo-clocks', name: 'Photo Clocks', slug: 'photo-clocks', Icon: Watch, dataAiHint: "wall clock custom" },
  { id: 'gift-hampers', name: 'Gift Hampers', slug: 'gift-hampers', Icon: Package, dataAiHint: "gift basket hamper" },
  { id: 'resin-art', name: 'Resin Art', slug: 'resin-art', Icon: Palette, dataAiHint: "epoxy resin craft" },
  { id: 'shadow-box', name: 'Shadow Box', slug: 'shadow-box', Icon: Package, dataAiHint: "3d shadow box frame" },
  { id: 'spotify-gifts', name: 'Spotify Gifts', slug: 'spotify-gifts', Icon: Music, dataAiHint: "spotify music plaque" },
  { id: 'heart-shaped-gifts', name: 'Heart Shaped Gifts', slug: 'heart-shaped-gifts', Icon: Heart, dataAiHint: "heart shape present" },
  { id: 'wooden-gifts', name: 'Wooden Gifts', slug: 'wooden-gifts', Icon: Shield, dataAiHint: "engraved wood item" },
  { id: 'chocolates', name: 'Chocolates', slug: 'chocolates', Icon: Gift, dataAiHint: "gourmet chocolate box" },

  { id: 'utility-mugs', name: 'Utility Gifts: Mugs', slug: 'utility-mugs', Icon: Utensils, dataAiHint: "custom coffee mug" },
  { id: 'utility-pens', name: 'Utility Gifts: Pens', slug: 'utility-pens', Icon: Pencil, dataAiHint: "engraved pen luxury" },
  { id: 'utility-t-shirts', name: 'Utility Gifts: T-Shirts', slug: 'utility-t-shirts', Icon: Shirt, dataAiHint: "custom printed tshirt" },
  { id: 'utility-bottles', name: 'Utility Gifts: Bottles', slug: 'utility-bottles', Icon: Package, dataAiHint: "personalized water bottle" },
  { id: 'utility-diaries', name: 'Utility Gifts: Diaries', slug: 'utility-diaries', Icon: Newspaper, dataAiHint: "custom journal diary" },
  { id: 'utility-keychains', name: 'Utility Gifts: Key Chains', slug: 'utility-keychains', Icon: Anchor, dataAiHint: "custom photo keychain" },

  { id: 'home-living-lamps', name: 'Home & Living: Lamps', slug: 'home-living-lamps', Icon: Lamp, dataAiHint: "decorative table lamp" }, // Could overlap photo-lamps
  { id: 'home-living-clocks', name: 'Home & Living: Clocks', slug: 'home-living-clocks', Icon: Watch, dataAiHint: "stylish wall clock" }, // Could overlap photo-clocks
  { id: 'home-living-cushions', name: 'Home & Living: Cushions', slug: 'home-living-cushions', Icon: ToyBrick, dataAiHint: "personalized photo cushion" },
  { id: 'home-living-bar-accessories', name: 'Home & Living: Bar Accessories', slug: 'home-living-bar-accessories', Icon: Wine, dataAiHint: "barware tools set" },
  { id: 'home-living-name-plates', name: 'Home & Living: Name Plates', slug: 'home-living-name-plates', Icon: Pin, dataAiHint: "custom door nameplate" },
  { id: 'home-living-magnets-tags', name: 'Home & Living: Magnets & Tags', slug: 'home-living-magnets-tags', Icon: Tag, dataAiHint: "fridge magnet custom" },
  { id: 'home-decor', name: 'Home Decor (General)', slug: 'home-decor', Icon: HomeIconLucide, dataAiHint: "stylish home decor" },


  // Mini You Series Sub-types
  { id: 'mini-you-bobbleheads', name: 'Mini You: Bobbleheads', slug: 'mini-you-bobbleheads', Icon: User, dataAiHint: "custom bobblehead doll" },
  { id: 'mini-you-caricatures', name: 'Mini You: Caricatures', slug: 'mini-you-caricatures', Icon: Smile, dataAiHint: "funny caricature art" },
  { id: 'mini-you-miniatures', name: 'Mini You: Full/Half Miniatures', slug: 'mini-you-miniatures', Icon: ToyBrick, dataAiHint: "3d selfie miniature" },
  { id: 'mini-you-framed-bobbleheads', name: 'Mini You: Framed Bobbleheads', slug: 'mini-you-framed-bobbleheads', Icon: User, dataAiHint: "bobblehead display case" },
  { id: 'mini-you-realistic-busts', name: 'Mini You: Realistic Busts', slug: 'mini-you-realistic-busts', Icon: User, dataAiHint: "custom bust statue" },


  // Corporate Gifts
  { id: 'corporate-awards', name: 'Corporate: Awards', slug: 'corporate-awards', Icon: Award, dataAiHint: "trophy plaque award" },
  { id: 'corporate-trophies', name: 'Corporate: Trophies', slug: 'corporate-trophies', Icon: Trophy, dataAiHint: "company trophy recognition" },
  { id: 'corporate-certificates', name: 'Corporate: Certificates', slug: 'corporate-certificates', Icon: Medal, dataAiHint: "achievement certificate frame" }, // Using Medal icon for variety
  { id: 'corporate-medals', name: 'Corporate: Medals', slug: 'corporate-medals', Icon: Medal, dataAiHint: "engraved medal award" },
  { id: 'corporate-mementos', name: 'Corporate: Mementos', slug: 'corporate-mementos', Icon: Gift, dataAiHint: "commemorative memento gift" },

  { id: 'corporate-apparel-tshirts', name: 'Corporate: T-Shirts', slug: 'corporate-apparel-tshirts', Icon: Shirt, dataAiHint: "branded company tshirt" },
  { id: 'corporate-apparel-caps', name: 'Corporate: Caps', slug: 'corporate-apparel-caps', Icon: Award, dataAiHint: "custom logo cap" }, // Using Award as a placeholder, could be specific cap icon if available
  { id: 'corporate-apparel-backpacks', name: 'Corporate: Backpacks', slug: 'corporate-apparel-backpacks', Icon: ShoppingBag, dataAiHint: "company logo backpack" },

  { id: 'corporate-joining-kits', name: 'Corporate: Joining Kits', slug: 'corporate-joining-kits', Icon: Package, dataAiHint: "employee welcome kit" },
  { id: 'corporate-joining-kits-2in1', name: 'Corporate: Joining Kits (2-in-1)', slug: 'corporate-joining-kits-2in1', Icon: Package, dataAiHint: "2in1 welcome set" },
  { id: 'corporate-joining-kits-3in1', name: 'Corporate: Joining Kits (3-in-1)', slug: 'corporate-joining-kits-3in1', Icon: Package, dataAiHint: "3in1 welcome set" },
  { id: 'corporate-joining-kits-4in1', name: 'Corporate: Joining Kits (4-in-1)', slug: 'corporate-joining-kits-4in1', Icon: Package, dataAiHint: "4in1 welcome set" },


  { id: 'corporate-stationery-stamps', name: 'Corporate: Rubber Stamps', slug: 'corporate-stationery-stamps', Icon: Pencil, dataAiHint: "company rubber stamp" },
  { id: 'corporate-stationery-pens', name: 'Corporate: Pens', slug: 'corporate-stationery-pens', Icon: Pencil, dataAiHint: "branded corporate pen" },
  { id: 'corporate-stationery-penstands', name: 'Corporate: Pen Stands', slug: 'corporate-stationery-penstands', Icon: Briefcase, dataAiHint: "desk pen holder" },
  { id: 'corporate-stationery-diaries', name: 'Corporate: Diaries', slug: 'corporate-stationery-diaries', Icon: Newspaper, dataAiHint: "custom logo diary" },
  { id: 'corporate-stationery-calendars', name: 'Corporate: Calendars', slug: 'corporate-stationery-calendars', Icon: CalendarDays, dataAiHint: "company desk calendar" },
  { id: 'corporate-stationery-cards', name: 'Corporate: ID & Visiting Cards', slug: 'corporate-stationery-cards', Icon: User, dataAiHint: "business visiting card" },

  { id: 'corporate-drinkware-bottles', name: 'Corporate: Bottles', slug: 'corporate-drinkware-bottles', Icon: Package, dataAiHint: "branded water bottle" },
  { id: 'corporate-drinkware-mugs', name: 'Corporate: Mugs', slug: 'corporate-drinkware-mugs', Icon: Utensils, dataAiHint: "company logo mug" },

  { id: 'corporate-utility-gift-sets', name: 'Corporate: Utility Gift Sets', slug: 'corporate-utility-gift-sets', Icon: Package, dataAiHint: "executive gift set" },
  { id: 'corporate-utility-desk-clocks', name: 'Corporate: Desk Clocks', slug: 'corporate-utility-desk-clocks', Icon: Watch, dataAiHint: "corporate desk clock" },
  { id: 'corporate-utility-desk-organizers', name: 'Corporate: Desk Organizers', slug: 'corporate-utility-desk-organizers', Icon: Briefcase, dataAiHint: "office desk organizer" },
  { id: 'corporate-utility-name-plates', name: 'Corporate: Name Plates', slug: 'corporate-utility-name-plates', Icon: Pin, dataAiHint: "desk name plate" },
  { id: 'corporate-utility-keychains', name: 'Corporate: Key Chains', slug: 'corporate-utility-keychains', Icon: Anchor, dataAiHint: "company logo keychain" },
  { id: 'corporate-utility-name-badges', name: 'Corporate: Name Badges', slug: 'corporate-utility-name-badges', Icon: User, dataAiHint: "employee name badge" },
  { id: 'apparel', name: 'Apparel (General)', slug: 'apparel', Icon: Shirt, dataAiHint: "clothing fashion style" },
  { id: 'stationery', name: 'Stationery (General)', slug: 'stationery', Icon: Pencil, dataAiHint: "office desk supplies" },
  { id: 'drinkware', name: 'Drinkware (General)', slug: 'drinkware', Icon: Utensils, dataAiHint: "cups bottles glasses" },
  { id: 'accessories', name: 'Accessories (General)', slug: 'accessories', Icon: SparklesIcon, dataAiHint: "fashion personal items" },
  { id: 'pet-gifts', name: 'Pet Gifts', slug: 'pet-gifts', Icon: Smile, dataAiHint: "dog cat toys" },
  { id: 'travel-gear', name: 'Travel Gear', slug: 'travel-gear', Icon: Plane, dataAiHint: "luggage travel essentials" },
  { id: 'sports-fitness', name: 'Sports & Fitness', slug: 'sports-fitness', Icon: Zap, dataAiHint: "gym equipment sports" },
  { id: 'outdoor-garden', name: 'Outdoor & Garden', slug: 'outdoor-garden', Icon: Sprout, dataAiHint: "plants garden tools" },
  { id: 'tech-gadgets', name: 'Tech & Gadgets', slug: 'tech-gadgets', Icon: Smartphone, dataAiHint: "electronic devices tech" },
  { id: 'event-supplies', name: 'Event Supplies', slug: 'event-supplies', Icon: Ticket, dataAiHint: "party wedding decor" },
];

export const RECIPIENTS_LIST: Recipient[] = [
  { id: 'men', name: 'Men (All)', slug: 'men', Icon: User, dataAiHint: "man silhouette" },
  { id: 'husband', name: 'Husband', slug: 'husband', Icon: Heart, dataAiHint: "loving couple husband" },
  { id: 'father', name: 'Father', slug: 'father', Icon: Award, dataAiHint: "father figure award" },
  { id: 'boyfriend', name: 'Boyfriend', slug: 'boyfriend', Icon: Rocket, dataAiHint: "romantic gift boyfriend" },
  { id: 'brother', name: 'Brother', slug: 'brother', Icon: Shield, dataAiHint: "siblings bond brother" },
  { id: 'son', name: 'Son', slug: 'son', Icon: GraduationCap, dataAiHint: "young boy son" },
  { id: 'male-friend', name: 'Male Friend', slug: 'male-friend', Icon: Users, dataAiHint: "friends group male" },
  { id: 'grandfather', name: 'Grandfather', slug: 'grandfather', Icon: User, dataAiHint: "elderly man grandfather" },
  { id: 'kids-boys', name: 'Kids (Boys)', slug: 'kids-boys', Icon: ToyBrick, dataAiHint: "playing boy child" },

  { id: 'women', name: 'Women (All)', slug: 'women', Icon: ShoppingBag, dataAiHint: "woman silhouette shopping" },
  { id: 'wife', name: 'Wife', slug: 'wife', Icon: Gem, dataAiHint: "happy couple wife" },
  { id: 'mother', name: 'Mother', slug: 'mother', Icon: Flower, dataAiHint: "motherly love flower" },
  { id: 'girlfriend', name: 'Girlfriend', slug: 'girlfriend', Icon: SparklesIcon, dataAiHint: "couple in love girlfriend" },
  { id: 'sister', name: 'Sister', slug: 'sister', Icon: Feather, dataAiHint: "sisters together feather" },
  { id: 'daughter', name: 'Daughter', slug: 'daughter', Icon: Star, dataAiHint: "young girl daughter" },
  { id: 'female-friend', name: 'Female Friend', slug: 'female-friend', Icon: Users, dataAiHint: "female friends group" },
  { id: 'grandmother', name: 'Grandmother', slug: 'grandmother', Icon: User, dataAiHint: "elderly woman grandmother" },
  { id: 'kids-girls', name: 'Kids (Girls)', slug: 'kids-girls', Icon: Smile, dataAiHint: "smiling girl child" },
  { id: 'couples', name: 'Couples', slug: 'couples', Icon: Users, dataAiHint: "romantic couple gift" },
  { id: 'winner', name: 'Winner', slug: 'winner', Icon: Trophy, dataAiHint: "trophy award winner" }, // Generic winner
  { id: 'employee', name: 'Employee', slug: 'employee', Icon: Briefcase, dataAiHint: "corporate employee gift"},
  { id: 'client', name: 'Client', slug: 'client', Icon: HandHeart, dataAiHint: "business client appreciation"},
  { id: 'teacher', name: 'Teacher', slug: 'teacher', Icon: GraduationCap, dataAiHint: "teacher appreciation gift"},
  { id: 'pet', name: 'Pet', slug: 'pet', Icon: Smile, dataAiHint: "dog cat pet gift"},
  { id: 'family', name: 'Family', slug: 'family', Icon: HomeIconLucide, dataAiHint: "family group gift" },
  { id: 'student', name: 'Student', slug: 'student', Icon: Book, dataAiHint: "student gift" }, // Assuming Book icon for Student
  { id: 'gamer', name: 'Gamer', slug: 'gamer', Icon: Gamepad, dataAiHint: "gamer gift" },
  { id: 'traveler', name: 'Traveler', slug: 'traveler', Icon: Plane, dataAiHint: "traveler gift" },
  { id: 'gardener', name: 'Gardener', slug: 'gardener', Icon: Leaf, dataAiHint: "gardener gift" },
  { id: 'homeowner', name: 'Homeowner', slug: 'homeowner', Icon: HomeIconLucide, dataAiHint: "homeowner gift" },
  { id: 'business', name: 'Business', slug: 'business', Icon: Briefcase, dataAiHint: "business gift" },
  { id: 'organizer', name: 'Organizer', slug: 'organizer', Icon: CalendarDays, dataAiHint: "event organizer gift" },
  { id: 'boss', name: 'Boss', slug: 'boss', Icon: Briefcase, dataAiHint: "boss gift" },
];

export const CATEGORIES: Category[] = GIFT_TYPES_LIST.map(gt => ({...gt}));

export const PRODUCTS: Product[] = [
  // Personalised Mugs from prestogifts.com/personalised-photo-coffee-mugs
  {
    id: 'mug_child_birthday_001',
    name: 'Personalised Mug For Child Birthday',
    description: 'Brighten a child\'s birthday with this fun, personalized ceramic mug. Add their name and a cheerful design!',
    price: 300,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'child birthday mug',
    category: 'utility-mugs',
    occasion: ['birthday', 'childrens-day'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 75,
    trending: true, // "24 People are Looking at This"
    slug: 'personalised-mug-child-birthday',
    customizable: true,
    soldBy: 'Just4UGifts',
    attributes: [{ name: 'Material', value: 'Ceramic' }, { name: 'Capacity', value: '11oz' }],
    reviews: [{id: 'rev_mug_cb_1', author: 'Parent1', rating: 5, comment: 'My kid loved it!', date: '2023-01-10'}],
  },
  {
    id: 'mug_valentine_ceramic_002',
    name: 'Custom Printable Ceramic Mug For Valentine’s Day',
    description: 'Express your love with a custom ceramic mug this Valentine\'s Day. Features your special photo and message.',
    price: 299,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'valentine mug custom',
    category: 'utility-mugs',
    occasion: ['valentines-day'],
    recipient: ['husband', 'wife', 'boyfriend', 'girlfriend', 'couples'],
    popularity: 88, // "Sold 27 times in the Last 48 Hours"
    trending: true,
    slug: 'custom-ceramic-mug-valentines',
    customizable: true,
    soldBy: 'Just4UGifts',
    attributes: [{ name: 'Material', value: 'Ceramic' }, { name: 'Print', value: 'Custom Photo & Text' }],
  },
  {
    id: 'mug_birthday_daughter_003',
    name: 'Custom Printable Birthday Mugs For Daughter',
    description: 'A special birthday mug for your beloved daughter. Personalize with her photo and a sweet message.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'daughter birthday mug',
    category: 'utility-mugs',
    occasion: ['birthday'],
    recipient: ['daughter', 'kids-girls'],
    popularity: 80, // "68 People are Looking at This"
    trending: true,
    slug: 'custom-birthday-mug-daughter',
    customizable: true,
  },
  {
    id: 'mug_baby_monkey_handle_004',
    name: 'Customised Baby Mug with Monkey Handle (4.2″×3.2″)',
    description: 'Adorable baby mug with a fun monkey handle. Perfect for little hands. Customizable with baby\'s name or photo.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'baby mug monkey',
    category: 'utility-mugs',
    occasion: ['baby-shower', 'birthday'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 70,
    slug: 'custom-baby-mug-monkey-handle',
    customizable: true,
    attributes: [{name: 'Size', value: '4.2" x 3.2"'}, {name: 'Handle', value: 'Monkey Shape'}]
  },
  {
    id: 'mug_magic_best_friend_005',
    name: 'Custom Printable Magic Mug for Best Friend',
    description: 'Surprise your best friend with a magic mug! The image appears when hot liquid is poured in.',
    price: 699,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'magic mug friend',
    category: 'utility-mugs',
    occasion: ['birthday', 'friendship-day'],
    recipient: ['male-friend', 'female-friend'],
    popularity: 90, // "57 People are Looking at This"
    trending: true,
    slug: 'custom-magic-mug-best-friend',
    customizable: true,
    attributes: [{name: 'Feature', value: 'Heat Activated Image Reveal'}]
  },
  {
    id: 'mug_fathers_day_color_inside_006',
    name: 'Father’s Day Colour Inside Mug',
    description: 'Show dad how much you care with this special Father\'s Day mug featuring a colorful interior.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'father day mug color',
    category: 'utility-mugs',
    occasion: ['fathers-day'],
    recipient: ['father', 'men'],
    popularity: 78,
    slug: 'fathers-day-color-inside-mug',
    customizable: true,
  },
  {
    id: 'mug_photo_cow_handle_007',
    name: 'Personalised Photo Mug with Cow Handle (4.2″×3.2″)',
    description: 'A charming personalized mug with a unique cow-shaped handle. Great for kids or animal lovers.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'photo mug cow',
    category: 'utility-mugs',
    occasion: ['birthday'],
    recipient: ['kids-boys', 'kids-girls', 'women', 'men'],
    popularity: 72,
    reviews: [{id:'rev_mug_cow_1', author: 'Happy Parent', rating: 5, comment: 'So cute!', date: '2023-02-15'}],
    slug: 'personalised-photo-mug-cow-handle',
    customizable: true,
  },
  {
    id: 'mug_valentine_custom_008',
    name: 'Custom Printable Mugs For Valentine',
    description: 'Another lovely option for Valentine\'s Day, fully customizable with your photos and messages.',
    price: 349,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'valentine mug custom print',
    category: 'utility-mugs',
    occasion: ['valentines-day'],
    recipient: ['husband', 'wife', 'boyfriend', 'girlfriend', 'couples'],
    popularity: 85,
    slug: 'custom-printable-mugs-valentine',
    customizable: true,
  },
  {
    id: 'mug_dolphin_handle_kids_009',
    name: 'Exclusive Custom Mug with Dolphin Handle for Kids (4.2″×3.2″)',
    description: 'Make drinking fun with this exclusive dolphin handle mug, personalized for your child.',
    price: 200,
    imageUrls: ['https://placehold.co/600x800.png', 'https://placehold.co/100x120.png'],
    dataAiHint: 'kids mug dolphin',
    category: 'utility-mugs',
    occasion: ['birthday', 'childrens-day'],
    recipient: ['kids-boys', 'kids-girls'],
    popularity: 82,
    slug: 'exclusive-custom-mug-dolphin-handle-kids-42x32',
    customizable: true,
  }
];

